project: 
  type: website
  output-dir: docs

website:
  title: "Cora Hirst Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Tidy Tuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
          - text: "Data Exercise"
            file: data-exercise/code/data-exercise.qmd
          - text: "Data Analysis Exercise"
            file: cdc-exercise/code/cdcdata-exercise.qmd
          - text: "Fitting Exercise"
            file: fitting-exercise/fitting-exercise.qmd
          - text: "Machine Learning Exercise I"
            file: ml-models-exercise/ml-models-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/CoraHirst/corahirst-MADA-portfolio       

format:
  html:
    theme: minty
    highlight: zenburn
    css: styles.css
    toc: FALSE


