<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Cora Hirst">

<title>Cora Hirst Data Analysis Portfolio - Fitting Exercise Week 8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Cora Hirst Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html" rel="" target="">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html" rel="" target="">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html" rel="" target="">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html" rel="" target="">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/code/data-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdc-exercise/code/cdcdata-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../fitting-exercise/fitting-exercise.html" rel="" target="">
 <span class="dropdown-text">Fitting Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/CoraHirst/corahirst-MADA-portfolio" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fitting Exercise Week 8</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Cora Hirst </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("tidyverse")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ggplot2")</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("tidymodels")</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("here")</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("rsample")</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="task-1-load-the-data-and-visualize" class="level2">
<h2 class="anchored" data-anchor-id="task-1-load-the-data-and-visualize">Task 1: load the data and visualize</h2>
<p>The code chunk below loads the <code>Mavoglurant_A2121_nmpk.csv</code> dataset and provides the structure and summary of its variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#read in csv file</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mavoglurant_data <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"Mavoglurant_A2121_nmpk.csv"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#take a look at the structure</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mavoglurant_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2678 obs. of  17 variables:
 $ ID  : int  793 793 793 793 793 793 793 793 793 793 ...
 $ CMT : int  1 2 2 2 2 2 2 2 2 2 ...
 $ EVID: int  1 0 0 0 0 0 0 0 0 0 ...
 $ EVI2: int  1 0 0 0 0 0 0 0 0 0 ...
 $ MDV : int  1 0 0 0 0 0 0 0 0 0 ...
 $ DV  : num  0 491 605 556 310 237 147 101 72.4 52.6 ...
 $ LNDV: num  0 6.2 6.41 6.32 5.74 ...
 $ AMT : num  25 0 0 0 0 0 0 0 0 0 ...
 $ TIME: num  0 0.2 0.25 0.367 0.533 0.7 1.2 2.2 3.2 4.2 ...
 $ DOSE: num  25 25 25 25 25 25 25 25 25 25 ...
 $ OCC : int  1 1 1 1 1 1 1 1 1 1 ...
 $ RATE: int  75 0 0 0 0 0 0 0 0 0 ...
 $ AGE : int  42 42 42 42 42 42 42 42 42 42 ...
 $ SEX : int  1 1 1 1 1 1 1 1 1 1 ...
 $ RACE: int  2 2 2 2 2 2 2 2 2 2 ...
 $ WT  : num  94.3 94.3 94.3 94.3 94.3 94.3 94.3 94.3 94.3 94.3 ...
 $ HT  : num  1.77 1.77 1.77 1.77 1.77 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mavoglurant_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ID             CMT             EVID              EVI2       
 Min.   :793.0   Min.   :1.000   Min.   :0.00000   Min.   :0.0000  
 1st Qu.:832.0   1st Qu.:2.000   1st Qu.:0.00000   1st Qu.:0.0000  
 Median :860.0   Median :2.000   Median :0.00000   Median :0.0000  
 Mean   :858.8   Mean   :1.926   Mean   :0.07394   Mean   :0.1613  
 3rd Qu.:888.0   3rd Qu.:2.000   3rd Qu.:0.00000   3rd Qu.:0.0000  
 Max.   :915.0   Max.   :2.000   Max.   :1.00000   Max.   :4.0000  
      MDV                DV               LNDV            AMT        
 Min.   :0.00000   Min.   :   0.00   Min.   :0.000   Min.   : 0.000  
 1st Qu.:0.00000   1st Qu.:  23.52   1st Qu.:3.158   1st Qu.: 0.000  
 Median :0.00000   Median :  74.20   Median :4.306   Median : 0.000  
 Mean   :0.09373   Mean   : 179.93   Mean   :4.085   Mean   : 2.763  
 3rd Qu.:0.00000   3rd Qu.: 283.00   3rd Qu.:5.645   3rd Qu.: 0.000  
 Max.   :1.00000   Max.   :1730.00   Max.   :7.456   Max.   :50.000  
      TIME             DOSE            OCC             RATE       
 Min.   : 0.000   Min.   :25.00   Min.   :1.000   Min.   :  0.00  
 1st Qu.: 0.583   1st Qu.:25.00   1st Qu.:1.000   1st Qu.:  0.00  
 Median : 2.250   Median :37.50   Median :1.000   Median :  0.00  
 Mean   : 5.851   Mean   :37.37   Mean   :1.378   Mean   : 16.55  
 3rd Qu.: 6.363   3rd Qu.:50.00   3rd Qu.:2.000   3rd Qu.:  0.00  
 Max.   :48.217   Max.   :50.00   Max.   :2.000   Max.   :300.00  
      AGE            SEX             RACE              WT        
 Min.   :18.0   Min.   :1.000   Min.   : 1.000   Min.   : 56.60  
 1st Qu.:26.0   1st Qu.:1.000   1st Qu.: 1.000   1st Qu.: 73.30  
 Median :31.0   Median :1.000   Median : 1.000   Median : 82.60  
 Mean   :32.9   Mean   :1.128   Mean   : 7.415   Mean   : 83.16  
 3rd Qu.:40.0   3rd Qu.:1.000   3rd Qu.: 2.000   3rd Qu.: 90.60  
 Max.   :50.0   Max.   :2.000   Max.   :88.000   Max.   :115.30  
       HT       
 Min.   :1.520  
 1st Qu.:1.710  
 Median :1.780  
 Mean   :1.762  
 3rd Qu.:1.820  
 Max.   :1.930  </code></pre>
</div>
</div>
<p>There are 17 variables and 2678 observations; some variables, such as <code>AGE</code>, <code>SEX</code>, <code>RACE</code>, <code>HT</code>, and <code>WT</code>, are descriptors of each individual <code>ID</code>; that is, the values of these variables will be the same for every observation with the same <code>ID</code> value.</p>
<p>There are multiple observations per <code>ID</code> level, each with different values for variables like <code>DV</code>, <code>LNDV</code>, and <code>TIME</code>; this suggests that the data is comprised of multiple time-series, with observations taken from the same individuals at different points of time.</p>
<p>Similarly, it appears that participants recieved one of three different dosages of Mavoglurant, and the <code>DV</code> aover time after administration of each dose is given. These time series are visualized in <a href="#fig-time-series">Figure&nbsp;1</a>, with <code>DV</code> as the outcome and faceted by <code>DOSE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#generate time series figure</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> mavoglurant_data, <span class="fu">aes</span>(<span class="at">x =</span> TIME, <span class="at">y =</span> DV, <span class="at">group =</span> ID, <span class="at">col =</span> <span class="fu">factor</span>(DOSE))) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">data =</span> mavoglurant_data, <span class="fu">aes</span>(<span class="at">x =</span> TIME, <span class="at">y =</span> DV, <span class="at">group =</span> ID, <span class="at">col =</span> <span class="fu">factor</span>(DOSE))) <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span> DOSE) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="st">"log"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="fitting-exercise_files/figure-html/generate-fig-time-series-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save Figure</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"time_series.png"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-time-series" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/time_series.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Initial visualization of DV time series per patient after administration of varying dosages of Mavoglurant.</figcaption>
</figure>
</div>
</div>
</div>
<p>Clearly, there is quite a bit of heterogeneity in these time series, through each tends to trend down more-or-less exponentially (though it seems the rate of decay is decreasing with time.) As indicated <a href="https://andreashandel.github.io/MADAcourse/content/model-fitting/assessment-model-fitting.html">here</a>, it appears that some indiciduals received the drug more than once, indicated by having both entries with <code>OCC</code> = 1 and <code>OCC</code> = 2. We will only be considering one dataset for each individual, and we will thus be keeping only 1 adminsitration, that is, <code>OCC</code> = 1.</p>
</section>
<section id="task-2-filtering-for-observations-with-occ-1-only" class="level2">
<h2 class="anchored" data-anchor-id="task-2-filtering-for-observations-with-occ-1-only">Task 2: Filtering for observations with <code>OCC</code> = 1 only</h2>
<p>The following code chunk removes all observations where <code>OCC</code> = 2. In all fairness, I am not removing <code>OCC</code> = 2 observations overtly. Instead, I am ensuring that I only keep <code>OCC</code> = 1 observations. This way, if we were to update the dataset with more observations from participants who received the drug a third or, even, a fourth time, we would only be analyzing one standard dataset across all participants.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#filter dataframe for observations after first administration of mavoglurant only</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>mavoglurant_data <span class="ot">=</span> mavoglurant_data <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(OCC <span class="sc">==</span> <span class="dv">1</span>) <span class="co"># keep OCC = 1 observations</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#note that I am trying to get into the habit of referencing a package each time I use a function derived from it, i.e dplyr::filter(). It's a challenge to remember to do so, but it will be worth it!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-3-isolating-t_0-observations-and-summing-total-dv-for-each-participant" class="level2">
<h2 class="anchored" data-anchor-id="task-3-isolating-t_0-observations-and-summing-total-dv-for-each-participant">Task 3: Isolating <span class="math inline">\(T_0\)</span> observations and summing total DV for each participant</h2>
<p>We would like to compute the total amount of drug (delivered?) for each participant by summing the <code>DV</code> values for each time series.</p>
<p><code>DV</code> is a measurment of drug concentration (presumably, drug in system, or drug delivered?). Because we are not going to use some sophisticated way of integrating to find the total drug amount (which makes me think this is total amount administered, but could also mean total amount in the blood over time), and instead we are going to sum DV over time, I’d like to get a sense of how much the length of the time series vary. If they vary dramatically, we should consider this when we draw conclusions based on total integrated <code>DV</code>.</p>
<p>The code chunk below generates a boxplot to compare the lengths of time series collected for participants, stratified by the dosage received.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#list to store time series lengths by dose</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>series_lengths <span class="ot">=</span> <span class="fu">list</span>()</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">levels</span>(<span class="fu">factor</span>(mavoglurant_data<span class="sc">$</span>DOSE)))){</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  lengths <span class="ot">=</span> mavoglurant_data <span class="sc">%&gt;%</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(DOSE <span class="sc">==</span> <span class="fu">levels</span>(<span class="fu">factor</span>(mavoglurant_data<span class="sc">$</span>DOSE))[i]) <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(ID) <span class="sc">%&gt;%</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(n)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  series_lengths[[i]] <span class="ot">=</span> lengths</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">lengths =</span> <span class="fu">c</span>(series_lengths[[<span class="dv">1</span>]], series_lengths[[<span class="dv">2</span>]], series_lengths[[<span class="dv">3</span>]]),</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">dose =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"25"</span>, <span class="fu">length</span>(series_lengths[[<span class="dv">1</span>]])), <span class="fu">rep</span>(<span class="st">"37.5"</span>, <span class="fu">length</span>(series_lengths[[<span class="dv">2</span>]])), <span class="fu">rep</span>(<span class="st">"50"</span>, <span class="fu">length</span>(series_lengths[[<span class="dv">3</span>]]))))</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x =</span> dose, <span class="at">y =</span> lengths, <span class="at">fill =</span> <span class="fu">factor</span>(dose))) <span class="co">#filling in boxplots looks cooler than outlining htem, in my opinion!</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Save Figure</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"time_series_lengthsbydose.png"</span>)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-time-series-lengthsbydose" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/time_series_lengthsbydose.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Boxplot of lengths of time series of participants by dose.</figcaption>
</figure>
</div>
</div>
</div>
<p>From <a href="#fig-time-series-lengthsbydose">Figure&nbsp;2</a>, it appears that time series collected for participants given a dose of 37.5 tend to be longer than the time series collected for participants given the other two dosages. However, the mean difference is 3 time points. If these time points occur <em>later</em> in the time series, when <code>DV</code> is significantly lower than the initial <code>DV</code> (<a href="#fig-time-series">Figure&nbsp;1</a>), the difference in the sum of <code>DV</code> values may not be too extreme; however, if these were to occur earlier in the time series compared to the other two dosages, when concentrations are high, then we’ve a reason to worry. This applies to the distribution of points collected at different times after original dose delivery, as well - if time series are long but all observations were made at a significantly longer time elapsed from time 0, then we’d have an artificially low sum. We are not going to address this issue moving forward (i.e by fitting to some function and integrating the model function under the length of the series), but I think it is particularly important to have a more visual and intuitive understanding of the issue.</p>
<p><strong>Perhaps I’ll revisit this after the model fitting portion of our exercise…</strong></p>
<p>The code chunk below calculates the sum of <code>DV</code> values for each time series collected for each dosage and stores these sums in a data frame object named <code>sums_nonzero</code>; the “nonzero” nomer distinguishes the dataframe on the basis that all initial <code>TIME</code> == 0 measurements are disregarded and not included in the sum.</p>
<p>For completeness, we also create a data frame of all initial observations, named <code>t0_obs</code>.</p>
<p>We join these together to generate a dataframe of size 120 x 18, which we will call <code>mavoglurant_data_cleaned</code>. In our <code>sums_nonzero</code> dataframe, we have one observation per ID, where a row lists the sum total <code>DV</code> across all time series points (excluding <code>TIME</code> == 0) for an ID. We also have one observation per ID in our <code>t0_obs</code> dataframe, which contains the initial <code>TIME</code> == 0 <code>DV</code> observation and other defining characteristics of this first observation for each participant <code>ID</code>. We can use <code>left_join()</code>, with <code>ID</code> as our primary key, to join these dataframes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># excluding observations with TIME == 0 and summing all DV per ID</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>sums_nonzero <span class="ot">=</span> mavoglurant_data <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TIME <span class="sc">!=</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">y =</span> <span class="fu">sum</span>(DV), <span class="at">.by =</span> ID)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># including only TIME == 0</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>t0_obs <span class="ot">=</span> mavoglurant_data <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TIME <span class="sc">==</span> <span class="dv">0</span>) </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># join the dfs</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>mavoglurant_data_cleaned <span class="ot">=</span> <span class="fu">left_join</span>(t0_obs, sums_nonzero, <span class="at">by =</span> <span class="st">"ID"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-4-cleaning-joined-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="task-4-cleaning-joined-dataframe">Task 4: Cleaning joined dataframe</h2>
<p>Lastly, we want to remove unnecessary variables from the joined dataframe <code>mavoglurant_data_cleaned</code> and convert categorical variables to type factor.</p>
<p>The code chunk below selects the <code>Y</code>, <code>DOSE</code>, <code>AGE</code>, <code>SEX</code>, <code>RACE</code>, <code>RATE</code>, <code>WT</code>, and <code>HT</code> variables, and treats <code>SEX</code> and <code>RACE</code> as factors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#finish cleaning df </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mavoglurant_data_cleaned <span class="ot">=</span> mavoglurant_data_cleaned <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(y, DOSE, RATE, AGE, SEX, RACE, WT, HT) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SEX =</span> <span class="fu">factor</span>(SEX), <span class="at">RACE =</span> <span class="fu">factor</span>(RACE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="model-fitting-continuous-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="model-fitting-continuous-outcomes">Model Fitting: continuous outcomes</h2>
<section id="dose-as-a-predictor-of-y" class="level3">
<h3 class="anchored" data-anchor-id="dose-as-a-predictor-of-y"><code>DOSE</code> as a predictor of <code>y</code></h3>
<p>Here, we know that <code>y</code> is the sum of our <code>DV</code> values after <code>TIME==0</code> for a time series. We also know that <code>DV</code> is related to drug concentration. So, we can already anticipate there will be some relationship between the initial <code>DOSE</code> and <code>y</code>.</p>
<p>The <code>DOSE</code> variable is <em>categorical</em> and the <code>y</code> variable is <em>continuous</em>, so I will try to visualize this anticipated relationship by plotting a boxplot of <code>y</code> for each <code>DOSE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">data =</span> mavoglurant_data_cleaned, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(DOSE), <span class="at">y =</span> y, <span class="at">fill =</span> <span class="fu">factor</span>(DOSE))) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> mavoglurant_data_cleaned, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(DOSE), <span class="at">y =</span> y)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Dose"</span>, <span class="at">y =</span> <span class="st">"DV at Time 0"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="fitting-exercise_files/figure-html/y-dose-scatterplot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Clearly, <code>y</code> appears to increase with <code>DOSE</code>. However, there is significant overlap between the points. While we can anticipate this trend is significant, we still have two goals for our model:</p>
<ol type="1">
<li>Can we parameterize the dependence of <code>y</code> on <code>DOSE</code> with some GLM (we can use a linear model)?</li>
<li>How significant is this relationship (we can use ANOVA on our linear model)?</li>
</ol>
<p>We would like to find a <em>linear model</em> to describe the relationship between <code>y</code> and <code>DOSE</code>, and we are fine to begin our fitting by looking for ordinary least squares. Thus, our model will take the form <code>y ~ DOSE</code>, will be linear with categorical predictor for continuous outcome, and we are fine with the <code>lm</code> method.</p>
<p>We can test whether the mean <code>y</code> predicted by <code>DOSE</code> is significantly different by dosage using ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">### fitting a linear model </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># define recipe with recipes package</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>rec_y_DOSE <span class="ot">&lt;-</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">recipe</span>(y <span class="sc">~</span> DOSE, </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> mavoglurant_data_cleaned)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># choose model with parsnip package</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>y_DOSE_reg <span class="ot">=</span> </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="co">#linear regression model</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span> <span class="co">#with lm method</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_mode</span>(<span class="st">"regression"</span>) <span class="co">#mode = regression, mode outcome is numeric</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn this into a workflow with workflows package</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>y_DOSE_reg_WF <span class="ot">=</span> </span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="co">#defining workflow object</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_model</span>(y_DOSE_reg) <span class="sc">%&gt;%</span> <span class="co">#choosing the model for the workflow</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_recipe</span>(rec_y_DOSE) <span class="co">#adding the recipe - which variables for outcome, predictor, any interactions...</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting the model with fit()</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>y_DOSE_reg_model <span class="ot">=</span> <span class="fu">fit</span>(y_DOSE_reg_WF, <span class="at">data =</span> mavoglurant_data_cleaned) </span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">=</span> y_DOSE_reg_model <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="do">### Testing if the mean ys are significantly different</span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>anova_y_DOSE_reg <span class="ot">=</span> y_DOSE_reg_model <span class="sc">%&gt;%</span> <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span> <span class="fu">anova</span>() </span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>table2 <span class="ot">=</span> anova_y_DOSE_reg <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a><span class="do">### saving table results </span></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a><span class="co"># save summary tables</span></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"y_DOSE_reg.rds"</span>)</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table1, <span class="at">file =</span> summarytable_file)</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"anova_y_DOSE_reg.rds"</span>)</span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table2, <span class="at">file =</span> summarytable_file)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-y-dose-reg" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1: Linear regression model of y predicted by DOSE.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">323.06249</td>
<td style="text-align: right;">199.048513</td>
<td style="text-align: right;">1.623034</td>
<td style="text-align: right;">0.1072508</td>
</tr>
<tr class="even">
<td style="text-align: left;">DOSE</td>
<td style="text-align: right;">58.21289</td>
<td style="text-align: right;">5.193797</td>
<td style="text-align: right;">11.208155</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The output of <code>tidymodel</code>’s <code>fit()</code> on our linear regression by <code>lm</code> model provides our estimated parameters (“estimate”, <a href="#tbl-y-dose-reg">Table&nbsp;1</a>), as well as the standard error (<span class="math inline">\(\sigma / \sqrt{n}\)</span>). Before we examine the results of our ANOVA, however, we want to take a closer look at the fit of othe linear model we fed into the analysis. Below, we use the <code>yardstick</code> package to determine the root mean squared error and correlation coefficient of the linear regression between <code>y</code> and <code>DOSE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate r^2 and RMSE from y_DOSE_reg model </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="do">## make predictions based on real DOSE observations </span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>predictions_y_DOSE_reg <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">predictor =</span> mavoglurant_data_cleaned<span class="sc">$</span>DOSE,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">.pred =</span> <span class="fu">predict</span>(y_DOSE_reg_model, <span class="at">new_data =</span> mavoglurant_data_cleaned <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>y)), <span class="co">#use regression model to make y predictions from existing DOSE observations</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">observation =</span> mavoglurant_data_cleaned<span class="sc">$</span>y) <span class="co">#bind to observed y observations</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="do">## lets take a look </span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> predictions_y_DOSE_reg, <span class="fu">aes</span>(<span class="at">x =</span> predictor, <span class="at">y =</span> observation, <span class="at">color =</span> <span class="fu">factor</span>(predictor))) <span class="sc">+</span> </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_point</span>(<span class="at">data =</span> predictions_y_DOSE_reg, <span class="fu">aes</span>(<span class="at">x =</span> predictor, <span class="at">y =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_line</span>(<span class="at">data =</span> predictions_y_DOSE_reg, <span class="fu">aes</span>(<span class="at">x =</span> predictor, <span class="at">y =</span> .pred), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>          <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Dose"</span>, <span class="at">y =</span> <span class="st">"DV sum"</span>, <span class="at">title =</span> <span class="st">"Regression model prediction of DV sum by dose"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="do">## now lets calculate our metrics</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">=</span> yardstick<span class="sc">::</span><span class="fu">metric_set</span>(rmse, rsq)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>table <span class="ot">=</span> <span class="fu">metrics</span>(predictions_y_DOSE_reg, <span class="at">truth =</span> observation, <span class="at">estimate =</span> .pred)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="do">## add rmse and rsq to plot </span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> plot <span class="sc">+</span> <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">y =</span> <span class="dv">5000</span>, <span class="at">x =</span> <span class="fl">32.5</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"RMSE = "</span>, <span class="fu">round</span>(table[<span class="dv">1</span>,<span class="dv">3</span>], <span class="dv">0</span>), <span class="st">"</span><span class="sc">\n</span><span class="st"> rsq = "</span>, <span class="fu">round</span>(table[<span class="dv">2</span>,<span class="dv">3</span>], <span class="dv">3</span>)))</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="co"># saving outputs</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"metrics_y_DOSE_reg.rds"</span>)</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table, <span class="at">file =</span> summarytable_file)</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"metrics_y_DOSE_reg.png"</span>)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-metrics-y-DOSE-reg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/metrics_y_DOSE_reg.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Scatterplot of total DV by Dose (colored) observed against estimated prediction (black).</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-metrics-y-DOSE-reg" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2: RMSE and r-squared for model prediction of DV sum by dose.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">666.4617870</td>
</tr>
<tr class="even">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.5156446</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Clearly, we can see that the linear regression captured some linear relationship between dose and the sum total DV, <code>y</code>. There is clearly quite a bit of variance among the observed values around the estimate predicted by our linear model for each dose (colored vs black points, <a href="#fig-metrics-y-DOSE-reg">Figure&nbsp;3</a>), and similarly, our model fit displays quite a high RMSE (666) and low <span class="math inline">\(r^2\)</span> (0.516).</p>
<p>The ANOVA does reveal that the differences in estimates from the regression model are significant, with a p-value of 2.6931057^{-20}. Let’s see if we can capture a better model by utilizing more variables as predictors.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-anova-y-dose-reg" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;3: Anova of regression estimated y by DOSE.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">sumsq</th>
<th style="text-align: right;">meansq</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DOSE</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">56743749</td>
<td style="text-align: right;">56743749.1</td>
<td style="text-align: right;">125.6227</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">53300558</td>
<td style="text-align: right;">451699.6</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="dose-rate-age-sex-race-ht-and-wt-as-predictors-of-y" class="level3">
<h3 class="anchored" data-anchor-id="dose-rate-age-sex-race-ht-and-wt-as-predictors-of-y"><code>DOSE</code>, <code>RATE</code>, <code>AGE</code>, <code>SEX</code>, <code>RACE</code>, <code>HT</code>, and <code>WT</code> as predictors of <code>y</code></h3>
<p>We’ve demonstrated that dose correlates positively with the sum total DV <code>y</code>; we’ve also demonstrated that there is quite a bit of heterogeneity around the estimate predicted by <code>DOSE</code> alone. Here, we would like to discern whether a model utilizing <code>DOSE</code>, <code>RATE</code>, AGE<code>,</code>SEX<code>,</code>RACE<code>,</code>HT<code>, and</code>WT<code>all as predictors of</code>y` will provide a better fitting model. This will ultimately raise the question of whether we are <em>overfitting</em> by introducing too many parameters, but let’s not get ahead of ourselves!</p>
<p>The questions addressed in this section are as follows:</p>
<ol type="1">
<li>Can we parameterize the dependence of <code>y</code> on <code>DOSE</code>, <code>RATE</code>, <code>AGE</code>, <code>SEX</code>, <code>RACE</code>, <code>HT</code>, and <code>WT</code> with some GLM (we can use a linear model)?</li>
<li>How do the RMSE and <span class="math inline">\(r^2\)</span> of this model compare to our previous <code>y ~ DOSE</code> regression?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">### fitting a linear model </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># define recipe with recipes package</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>rec_y_all <span class="ot">&lt;-</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">recipe</span>(y <span class="sc">~</span> DOSE <span class="sc">+</span> RATE <span class="sc">+</span> AGE <span class="sc">+</span> SEX <span class="sc">+</span> RACE <span class="sc">+</span> WT <span class="sc">+</span> HT, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> mavoglurant_data_cleaned)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># choose model with parsnip package</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>y_all_reg <span class="ot">=</span> </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="co">#linear regression model</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span> <span class="co">#with lm method</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_mode</span>(<span class="st">"regression"</span>) <span class="co">#mode = regression, mode outcome is numeric</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn this into a workflow with workflows package</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>y_all_reg_WF <span class="ot">=</span> </span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="co">#defining workflow object</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_model</span>(y_all_reg) <span class="sc">%&gt;%</span> <span class="co">#choosing the model for the workflow</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_recipe</span>(rec_y_all) <span class="co">#adding the recipe - which variables for outcome, predictor, any interactions...</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting the model with fit()</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>y_all_reg_model <span class="ot">=</span> <span class="fu">fit</span>(y_all_reg_WF, <span class="at">data =</span> mavoglurant_data_cleaned) </span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">=</span> y_all_reg_model <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a><span class="do">### saving table results </span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a><span class="co"># save summary tables</span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"y_all_reg.rds"</span>)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table1, <span class="at">file =</span> summarytable_file)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-y-all-reg" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;4: Linear regression model of sum total DV predicted by <code>DOSE</code>, <code>RATE</code>, <code>AGE</code>, <code>SEX</code>, <code>RACE</code>, <code>HT</code>, and <code>WT</code>.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3399.953281</td>
<td style="text-align: right;">1819.271104</td>
<td style="text-align: right;">1.8688547</td>
<td style="text-align: right;">0.0643032</td>
</tr>
<tr class="even">
<td style="text-align: left;">DOSE</td>
<td style="text-align: right;">146.874595</td>
<td style="text-align: right;">50.861892</td>
<td style="text-align: right;">2.8877139</td>
<td style="text-align: right;">0.0046733</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RATE</td>
<td style="text-align: right;">-14.354042</td>
<td style="text-align: right;">8.359358</td>
<td style="text-align: right;">-1.7171225</td>
<td style="text-align: right;">0.0887711</td>
</tr>
<tr class="even">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">1.777301</td>
<td style="text-align: right;">7.798316</td>
<td style="text-align: right;">0.2279083</td>
<td style="text-align: right;">0.8201406</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SEX2</td>
<td style="text-align: right;">-338.676786</td>
<td style="text-align: right;">215.335328</td>
<td style="text-align: right;">-1.5727878</td>
<td style="text-align: right;">0.1186399</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACE2</td>
<td style="text-align: right;">125.040505</td>
<td style="text-align: right;">128.703178</td>
<td style="text-align: right;">0.9715417</td>
<td style="text-align: right;">0.3334101</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACE7</td>
<td style="text-align: right;">-398.431716</td>
<td style="text-align: right;">444.324300</td>
<td style="text-align: right;">-0.8967138</td>
<td style="text-align: right;">0.3718300</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACE88</td>
<td style="text-align: right;">-69.064910</td>
<td style="text-align: right;">242.717190</td>
<td style="text-align: right;">-0.2845489</td>
<td style="text-align: right;">0.7765248</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WT</td>
<td style="text-align: right;">-23.703602</td>
<td style="text-align: right;">6.351282</td>
<td style="text-align: right;">-3.7320972</td>
<td style="text-align: right;">0.0003023</td>
</tr>
<tr class="even">
<td style="text-align: left;">HT</td>
<td style="text-align: right;">-717.053335</td>
<td style="text-align: right;">1094.568090</td>
<td style="text-align: right;">-0.6551016</td>
<td style="text-align: right;">0.5137700</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Clearly, <code>DOSE</code>, <code>RATE</code>, and <code>WT</code> are significant predictors of the sum total DV (<a href="#tbl-y-all-reg">Table&nbsp;4</a>).</p>
<p>However, when we observe our metrics:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate r^2 and RMSE from y_DOSE_reg model </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="do">## make predictions based on real DOSE observations </span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>predictions_y_all_reg <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">predictor_1=</span> mavoglurant_data_cleaned<span class="sc">$</span>DOSE,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">.pred =</span> <span class="fu">predict</span>(y_all_reg_model, <span class="at">new_data =</span> mavoglurant_data_cleaned <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>y)), <span class="co">#use regression model to make y predictions from existing observations</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">observation =</span> mavoglurant_data_cleaned<span class="sc">$</span>y) <span class="co">#bind to observed y observations</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                                    </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="do">## lets take a look </span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> predictions_y_all_reg, <span class="fu">aes</span>(<span class="at">x =</span> observation, <span class="at">y =</span> .pred, <span class="at">color =</span> <span class="fu">factor</span>(predictor_1))) <span class="sc">+</span> </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_abline</span>(<span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>          <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Observed"</span>, <span class="at">y =</span> <span class="st">"Predicted"</span>, <span class="at">title =</span> <span class="st">"DV sums observed and predicted by regression"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="do">## now lets calculate our metrics</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">=</span> yardstick<span class="sc">::</span><span class="fu">metric_set</span>(rmse, rsq)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>table <span class="ot">=</span> <span class="fu">metrics</span>(predictions_y_all_reg, <span class="at">truth =</span> observation, <span class="at">estimate =</span> .pred)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="do">## add rmse and rsq to plot </span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> plot <span class="sc">+</span> <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">y =</span> <span class="dv">5000</span>, <span class="at">x =</span> <span class="dv">2000</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"RMSE = "</span>, <span class="fu">round</span>(table[<span class="dv">1</span>,<span class="dv">3</span>], <span class="dv">0</span>), <span class="st">"</span><span class="sc">\n</span><span class="st"> rsq = "</span>, <span class="fu">round</span>(table[<span class="dv">2</span>,<span class="dv">3</span>], <span class="dv">3</span>)))</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co"># saving outputs</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"metrics_y_all_reg.rds"</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table, <span class="at">file =</span> summarytable_file)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"metrics_y_all_reg.png"</span>)</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-metrics-y-all-reg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/metrics_y_all_reg.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Scatterplot of total DV observed against estimated prediction, colored by dose. Diagonal dashed line shows 1:1 corelation</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-metrics-y-all-reg" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;5: RMSE and r-squared for model prediction of DV sum by all predictor variables.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">583.0903868</td>
</tr>
<tr class="even">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.6292464</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><a href="#tbl-metrics-y-all-reg">Table&nbsp;5</a> reveals that a model utilizing all variables as predictors of total DV sums does a slightly better job at recapitulating our observed <code>y</code> values, explaining 63% of the variance as opposed to the 52% explained by <code>DOSE</code> alone. However, if we were to penalize for the number of predictors and parameters, I’m not sure we’d agree that this model is the better-fitting! Once again, this depends on our goal - do we wish to reproduce our observations with the greatest accuracy? If we were to sample smaller subsets of our data and refit, would we still be able to reproduce all of our results with the same accuracy, and how much variance would we observe in the estimated parameters of each iteration?</p>
<!-- this might be something to try in the future! -->
</section>
</section>
<section id="model-fitting-categorical-outcome" class="level2">
<h2 class="anchored" data-anchor-id="model-fitting-categorical-outcome">Model fitting: categorical outcome</h2>
<p>Previously, we formulated two linear models to predict the continuous outcome of the sum total DV for each time series, which we called <code>y</code>, with either initial drug <code>DOSE</code> alone or all predictor variables as predictors. This led us to ask an interesting question: do we care the most about accuracy, precision, and/or biological meaning in our model?</p>
<p>Here, we would like to ask a similar question: can we accurately predict the sex of an individual based upon the dosage of the drug they recieved? If we fit a model with all of their other characteristic variables, will we see a greater fit, and will this greater fit be meaningful enough that we would opt for the more parameterized model?</p>
<p>Here, <code>SEX</code> is a categorical variable we intend to predict; as such, we can use a logistic model. We will be using the default threshold of 0.5 as a cutoff to categorize our participants as either<code>SEX</code> == 1, or “success” (so it’s probably women ;)), or <code>SEX</code> == 2, or failure.</p>
<section id="predicting-sex-by-dose" class="level3">
<h3 class="anchored" data-anchor-id="predicting-sex-by-dose">Predicting <code>SEX</code> by <code>DOSE</code></h3>
<p>Here, we’d like to see how well we can fit a logistic model to <code>SEX</code> by the predictor <code>DOSE</code>; perhaps certain dosages are more frequently assigned to one sex than the other? <code>SEX</code> is a binary categorical variable, and <code>DOSE</code> is a categorical variable with more than two levels. We will thus use a logistic regression to classify observations into either <code>SEX</code> category, 0 or 1.</p>
<p>The logistic regression estimates 2 parameters to produce a steep sigmoidal probability of one category of a binary categorical variable and some continuous predictor ( or some probability of success based on categorical predictors). The two parameters produce a sigmoidal relationship by assuming the <em>odds</em> of success increase multiplicatively for some unit increase in the predictor (that is, the natural log of the odds function of success is linear). For myself and others, a wonderful resource explaining the inutition behind this can be found in <a href="https://bradleyboehmke.github.io/HOML/logistic-regression.html">this online chapter</a>.</p>
<p>If the predictor is continuous, we’d see something along the lines (ha, pun intended) of <a href="#fig-logistic-example">Figure&nbsp;5</a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">### fitting a linear model </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># define recipe with recipes package</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>recipe <span class="ot">&lt;-</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">recipe</span>(SEX <span class="sc">~</span> HT, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> mavoglurant_data_cleaned)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># choose model with parsnip package</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">=</span> </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span> <span class="co">#linear regression model</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">%&gt;%</span> <span class="co">#with glm method - which we cant use lm for a logistic model becuase OLS-like statstics don't make much sense here!</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_mode</span>(<span class="st">"classification"</span>) <span class="co">#mode = classification, mode outcome is categorical</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn this into a workflow with workflows package</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>reg_WF <span class="ot">=</span> </span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="co">#defining workflow object</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_model</span>(reg) <span class="sc">%&gt;%</span> <span class="co">#choosing the model for the workflow</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_recipe</span>(recipe) <span class="co">#adding the recipe - which variables for outcome, predictor, any interactions...</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>reg_model <span class="ot">=</span> <span class="fu">fit</span>(reg_WF, <span class="at">data =</span> mavoglurant_data_cleaned) </span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">=</span> reg_model <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="do">###plot </span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> mavoglurant_data_cleaned, <span class="fu">aes</span>(<span class="at">x =</span> HT, <span class="at">y =</span> (<span class="fu">as.numeric</span>(SEX))<span class="sc">-</span><span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(table1<span class="sc">$</span>estimate[<span class="dv">1</span>] <span class="sc">+</span> table1<span class="sc">$</span>estimate[<span class="dv">2</span>]<span class="sc">*</span>x)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(table1<span class="sc">$</span>estimate[<span class="dv">1</span>] <span class="sc">+</span> table1<span class="sc">$</span>estimate[<span class="dv">2</span>]<span class="sc">*</span>x))) <span class="sc">+</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"HT"</span>, <span class="at">y =</span> <span class="st">"probability of Sex 2"</span>, <span class="at">title =</span> <span class="st">"Example Logistic Regression"</span>)</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a><span class="do">###save fig</span></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"logistic_example.png"</span>)</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-logistic-example" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/logistic_example.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Example of a logistic regression categorizing SEX by the continuous variable HT (height?)</figcaption>
</figure>
</div>
</div>
</div>
<p>Note that we can also perform a logistic regression utilizing a categorical predictor - and, here, we can treat <code>DOSE</code> as a categorical variable or a numeric variable. I will be treating it numerically, because increasing dosage can have biological significance which may be indicated by sexual dimorphism!</p>
<p>Here, we are preforming a logistic regression to predict the probability of belonging to <code>SEX</code> category 2 based on the variable <code>DOSE</code>. Our formula will be <code>SEX ~ DOSE</code>, we will use a <code>logistic_reg()</code> model with an <code>glm</code> “engine”, and the mode of our model is <code>classification</code> as the output variable is categorical.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">### fitting a linear model </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># define recipe with recipes package</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>recipe <span class="ot">&lt;-</span> </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">recipe</span>(SEX <span class="sc">~</span> DOSE, </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> mavoglurant_data_cleaned)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># choose model with parsnip package</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">=</span> </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span> <span class="co">#linear regression model</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">%&gt;%</span> <span class="co">#with glm method - which we cant use lm for a logistic model becuase OLS-like statstics don't make much sense here!</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_mode</span>(<span class="st">"classification"</span>) <span class="co">#mode = classification, mode outcome is categorical</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn this into a workflow with workflows package</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>reg_WF <span class="ot">=</span> </span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="co">#defining workflow object</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_model</span>(reg) <span class="sc">%&gt;%</span> <span class="co">#choosing the model for the workflow</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_recipe</span>(recipe) <span class="co">#adding the recipe - which variables for outcome, predictor, any interactions...</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>reg_model <span class="ot">=</span> <span class="fu">fit</span>(reg_WF, <span class="at">data =</span> mavoglurant_data_cleaned) </span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">=</span> reg_model <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a><span class="do">###plot </span></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> mavoglurant_data_cleaned, <span class="fu">aes</span>(<span class="at">x =</span> DOSE, <span class="at">y =</span> (<span class="fu">as.numeric</span>(SEX))<span class="sc">-</span><span class="dv">1</span>, <span class="at">color =</span> SEX), <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span> </span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(table1<span class="sc">$</span>estimate[<span class="dv">1</span>] <span class="sc">+</span> table1<span class="sc">$</span>estimate[<span class="dv">2</span>]<span class="sc">*</span>x)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(table1<span class="sc">$</span>estimate[<span class="dv">1</span>] <span class="sc">+</span> table1<span class="sc">$</span>estimate[<span class="dv">2</span>]<span class="sc">*</span>x))) <span class="sc">+</span></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"DOSE"</span>, <span class="at">y =</span> <span class="st">"probability of Sex 2"</span>, <span class="at">title =</span> <span class="st">"Logistic Regression of Sex 2 Prob by Dose"</span>)</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a><span class="do">### saving table results </span></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a><span class="co"># save summary tables</span></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"SEX_DOSE_reg.rds"</span>)</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table1, <span class="at">file =</span> summarytable_file)</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a><span class="do">###save fig</span></span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"logistic_sex_dose.png"</span>)</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-logistic-sex-dose" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/logistic_sex_dose.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Logistic regression categorizing SEX by the variable DOSE. Opacity of point indicates number of observations for each sex at each DOSE. Black line indicates logistic regression curve.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-logistic-sex-dose" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;6: Logistic regression model to categorize SEX by DOSE, success: SEX == 2.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.7648181</td>
<td style="text-align: right;">0.8539475</td>
<td style="text-align: right;">-0.8956266</td>
<td style="text-align: right;">0.3704522</td>
</tr>
<tr class="even">
<td style="text-align: left;">DOSE</td>
<td style="text-align: right;">-0.0317544</td>
<td style="text-align: right;">0.0243205</td>
<td style="text-align: right;">-1.3056660</td>
<td style="text-align: right;">0.1916662</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Evidently, <code>DOSE</code> is a pretty poor predictor (say that five times fast) of <code>SEX</code> (see p.values for parameter estimates, <a href="#tbl-logistic-sex-dose">Table&nbsp;6</a>). This is certainly not helped by the potential that <code>SEX</code> category 1 is over-represented in the dataset (see opacity of points, <a href="#fig-logistic-sex-dose">Figure&nbsp;6</a>). (Perhaps mavolglurant is a drug used more by one sex than the other?)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate r^2 and RMSE from y_DOSE_reg model </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="do">## make predictions based on real DOSE observations </span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">predictor =</span> mavoglurant_data_cleaned<span class="sc">$</span>DOSE,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">.pred =</span> <span class="fu">predict</span>(reg_model, <span class="at">new_data =</span> mavoglurant_data_cleaned <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>SEX)), <span class="co">#use regression model to make SEX predictions from existing DOSE observations</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">observation =</span> mavoglurant_data_cleaned<span class="sc">$</span>SEX) <span class="co">#bind to observed sex observations</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co">#plot barplot</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> predictions <span class="sc">%&gt;%</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(predictor) <span class="sc">%&gt;%</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">obs_succeses =</span> <span class="fu">sum</span>(<span class="fu">as.numeric</span>(observation)), <span class="at">pred_successes =</span> <span class="fu">sum</span>(<span class="fu">as.numeric</span>(.pred_class))) <span class="sc">%&gt;%</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"obs_succeses"</span>, <span class="st">"pred_successes"</span>),</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"data"</span>, </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"SEX2_Count"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(predictor), <span class="at">y =</span> SEX2_Count, <span class="at">fill =</span> data)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"DOSE"</span>, <span class="at">y =</span> <span class="st">"Count of Sex 2 participants"</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="do">## now lets calculate our metrics</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="do">### accuracy</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>acc <span class="ot">=</span> <span class="fu">accuracy</span>(predictions, <span class="at">truth =</span> observation, <span class="at">estimate =</span> .pred_class)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="do">### ROC AUC</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">predictor =</span> mavoglurant_data_cleaned<span class="sc">$</span>DOSE,</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>                                    <span class="fu">predict</span>(reg_model, <span class="at">new_data =</span> mavoglurant_data_cleaned <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>SEX), <span class="at">type =</span> <span class="st">"prob"</span>), <span class="co">#use regression model to make SEX predictions from existing DOSE observations, returns probabilities of sex categories (2 cols)</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">observation =</span> mavoglurant_data_cleaned<span class="sc">$</span>SEX) <span class="co">#bind to observed sex observations</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>rocauc <span class="ot">=</span> <span class="fu">roc_auc</span>(predictions, <span class="at">truth =</span> observation, .pred_1) <span class="co">#roc with probabiliy of sex 2 thresholds</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">=</span> <span class="fu">roc_curve</span>(predictions, <span class="at">truth =</span> observation, .pred_1) <span class="sc">%&gt;%</span> <span class="co">#plot roc curve</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>               <span class="fu">autoplot</span>() <span class="sc">+</span> <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.75</span>, <span class="at">y =</span> <span class="fl">0.25</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"AUC = "</span>, <span class="fu">round</span>(rocauc<span class="sc">$</span>.estimate, <span class="dv">3</span>)))</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="do">## adjust barplot with accuracy metrics </span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> plot <span class="sc">+</span> <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="st">"50"</span>, <span class="at">y =</span> <span class="dv">60</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"accuracy = "</span>, <span class="fu">round</span>(acc<span class="sc">$</span>.estimate, <span class="dv">3</span>)))</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a><span class="co">#save figures</span></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"metrics_sex_DOSE_reg.png"</span>)</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"roc_sex_DOSE_reg.png"</span>)</span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot2) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-metrics-sex-DOSE-reg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/metrics_sex_DOSE_reg.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Barplot of observed Sex 2 counts (orange) against estimated prediction (blue).</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-roc-sex-DOSE-reg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/roc_sex_DOSE_reg.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;8: ROC curve of sensitivity vs specificity in correctly categorizing observations by SEX from DOSE predictor, probability threshold = 0.5 .</figcaption>
</figure>
</div>
</div>
</div>
<!-- get a good understanding of what this curve shows -->
<p>The accuracy is actually pretty high (<a href="#fig-metrics-sex-DOSE-reg">Figure&nbsp;7</a>) at 0.867, though our p-value really isn’t.</p>
</section>
<section id="predicting-sex-by-dose-rate-age-sex-race-ht-wt-and-y." class="level3">
<h3 class="anchored" data-anchor-id="predicting-sex-by-dose-rate-age-sex-race-ht-wt-and-y.">Predicting <code>SEX</code> by <code>DOSE</code>, <code>RATE</code>, <code>AGE</code>, <code>SEX</code>, <code>RACE</code>, <code>HT</code>, <code>WT</code>, and <code>y</code>.</h3>
<p>The code chunk below fits a logistic regression model to predict <code>SEX</code> by the predictors <code>DOSE</code>, <code>RATE</code>, <code>AGE</code>, <code>SEX</code>, <code>RACE</code>, <code>HT</code>, <code>WT</code>, and <code>y</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">### fitting a linear model </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># define recipe with recipes package</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>recipe <span class="ot">&lt;-</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">recipe</span>(SEX <span class="sc">~</span> DOSE <span class="sc">+</span> RATE <span class="sc">+</span> AGE <span class="sc">+</span> y <span class="sc">+</span> RACE <span class="sc">+</span> WT <span class="sc">+</span> HT, </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> mavoglurant_data_cleaned)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># choose model with parsnip package</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">=</span> </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span> <span class="co">#linear regression model</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">%&gt;%</span> <span class="co">#with glm method - which we cant use lm for a logistic model becuase OLS-like statstics don't make much sense here!</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_mode</span>(<span class="st">"classification"</span>) <span class="co">#mode = classification, mode outcome is categorical</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn this into a workflow with workflows package</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>reg_WF <span class="ot">=</span> </span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="co">#defining workflow object</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_model</span>(reg) <span class="sc">%&gt;%</span> <span class="co">#choosing the model for the workflow</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_recipe</span>(recipe) <span class="co">#adding the recipe - which variables for outcome, predictor, any interactions...</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>reg_model <span class="ot">=</span> <span class="fu">fit</span>(reg_WF, <span class="at">data =</span> mavoglurant_data_cleaned) </span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">=</span> reg_model <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="do">###plot </span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> mavoglurant_data_cleaned, <span class="fu">aes</span>(<span class="at">x =</span> HT, <span class="at">y =</span> (<span class="fu">as.numeric</span>(SEX))<span class="sc">-</span><span class="dv">1</span>, <span class="at">color =</span> AGE, <span class="at">shape =</span> RACE)) <span class="sc">+</span> </span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(table1<span class="sc">$</span>estimate[<span class="dv">1</span>] <span class="sc">+</span> table1<span class="sc">$</span>estimate[<span class="dv">10</span>]<span class="sc">*</span>x)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(table1<span class="sc">$</span>estimate[<span class="dv">1</span>] <span class="sc">+</span> table1<span class="sc">$</span>estimate[<span class="dv">10</span>]<span class="sc">*</span>x))) <span class="sc">+</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"HT"</span>, <span class="at">y =</span> <span class="st">"probability of Sex 2"</span>, <span class="at">title =</span> <span class="st">"Logistic Regression, Probability of Sex 2 by all descriptors"</span>)</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a><span class="do">### saving table results </span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="co"># save summary tables</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"SEX_all_reg.rds"</span>)</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table1, <span class="at">file =</span> summarytable_file)</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a><span class="do">###save fig</span></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"logistic_sex_all.png"</span>)</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-logistic-sex-all" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/logistic_sex_all.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;9: Logistic regression categorizing SEX by all other predictor variables in the <code>mavoglurant_data_cleaned</code> dataframe. Point color indicates age, while point shape indicates race category. The regression line for continuous predictor height is plotted.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-logistic-sex-all" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;7: Logistic regression model to categorize SEX by all predictor variables, success: SEX == 2.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">60.2826915</td>
<td style="text-align: right;">18.0502582</td>
<td style="text-align: right;">3.3397135</td>
<td style="text-align: right;">0.0008386</td>
</tr>
<tr class="even">
<td style="text-align: left;">DOSE</td>
<td style="text-align: right;">-0.8490976</td>
<td style="text-align: right;">191.9637237</td>
<td style="text-align: right;">-0.0044232</td>
<td style="text-align: right;">0.9964708</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RATE</td>
<td style="text-align: right;">0.1363655</td>
<td style="text-align: right;">31.9939454</td>
<td style="text-align: right;">0.0042622</td>
<td style="text-align: right;">0.9965992</td>
</tr>
<tr class="even">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">0.0834182</td>
<td style="text-align: right;">0.0607202</td>
<td style="text-align: right;">1.3738127</td>
<td style="text-align: right;">0.1694998</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y</td>
<td style="text-align: right;">-0.0010377</td>
<td style="text-align: right;">0.0009642</td>
<td style="text-align: right;">-1.0763124</td>
<td style="text-align: right;">0.2817876</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACE2</td>
<td style="text-align: right;">-1.9240578</td>
<td style="text-align: right;">1.3759139</td>
<td style="text-align: right;">-1.3983854</td>
<td style="text-align: right;">0.1619974</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACE7</td>
<td style="text-align: right;">0.1185532</td>
<td style="text-align: right;">3.8410314</td>
<td style="text-align: right;">0.0308649</td>
<td style="text-align: right;">0.9753773</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACE88</td>
<td style="text-align: right;">-1.4978163</td>
<td style="text-align: right;">2.1944584</td>
<td style="text-align: right;">-0.6825449</td>
<td style="text-align: right;">0.4948945</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WT</td>
<td style="text-align: right;">-0.0626504</td>
<td style="text-align: right;">0.0794790</td>
<td style="text-align: right;">-0.7882638</td>
<td style="text-align: right;">0.4305424</td>
</tr>
<tr class="even">
<td style="text-align: left;">HT</td>
<td style="text-align: right;">-33.1798562</td>
<td style="text-align: right;">11.0835782</td>
<td style="text-align: right;">-2.9936051</td>
<td style="text-align: right;">0.0027570</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The best predictors of of <code>SEX</code> appear to be <code>HT</code>, <code>Race</code>, <code>AGE</code>, and potentially <code>y</code> (<a href="#tbl-logistic-sex-all">Table&nbsp;7</a>).<code>Dose</code>, <code>y</code>, <code>RACE</code>==32 or 88, <code>WT</code>, and <code>HT</code> are negatively correlated with <code>SEX==2</code>. Biologically, if we consider women to be shorter than men on average, then maybe my choice of <code>SEX</code> == 2 as the “success” variable under the assumption that <code>SEX</code> 2 is women was fortuitous ;).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate r^2 and RMSE from y_DOSE_reg model </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="do">## make predictions based on real DOSE observations </span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">predictor =</span> mavoglurant_data_cleaned<span class="sc">$</span>HT,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">.pred =</span> <span class="fu">predict</span>(reg_model, <span class="at">new_data =</span> mavoglurant_data_cleaned <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>SEX)), <span class="co">#use regression model to make SEX predictions from existing DOSE observations</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">observation =</span> mavoglurant_data_cleaned<span class="sc">$</span>SEX) <span class="co">#bind to observed sex observations</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">#plot barplot</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>observed_successes <span class="ot">=</span> predictions <span class="sc">%&gt;%</span> <span class="fu">select</span>(predictor, observation) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(observation<span class="sc">==</span><span class="dv">2</span>) </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>predicted_successes <span class="ot">=</span> predictions <span class="sc">%&gt;%</span> <span class="fu">select</span>(predictor, .pred_class) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(.pred_class<span class="sc">==</span><span class="dv">2</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>for_hist <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">HT =</span> <span class="fu">c</span>(observed_successes<span class="sc">$</span>predictor, predicted_successes<span class="sc">$</span>predictor),</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">count =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"observed"</span>, <span class="fu">nrow</span>(observed_successes)), <span class="fu">rep</span>(<span class="st">"predicted"</span>, <span class="fu">nrow</span>(predicted_successes))))</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> for_hist <span class="sc">%&gt;%</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> HT, <span class="at">y =</span> ..density.., <span class="at">color =</span> count, <span class="at">fill =</span> count), <span class="at">alpha =</span> <span class="fl">0.25</span>, <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">bins =</span> <span class="dv">20</span>) <span class="sc">+</span> </span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> HT, <span class="at">y=</span>..density.., <span class="at">color =</span> count, <span class="at">fill =</span> count), <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"HT"</span>, <span class="at">y =</span> <span class="st">"density of total SEX == 2 observations"</span>, <span class="at">title =</span> <span class="st">"Comparison of classifications of SEX by Logistic regression model against predictor HT"</span>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="do">## now lets calculate our metrics</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="do">### accuracy</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>acc <span class="ot">=</span> <span class="fu">accuracy</span>(predictions, <span class="at">truth =</span> observation, <span class="at">estimate =</span> .pred_class)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a><span class="do">### ROC AUC</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">predictor =</span> mavoglurant_data_cleaned<span class="sc">$</span>HT,</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>                                    <span class="fu">predict</span>(reg_model, <span class="at">new_data =</span> mavoglurant_data_cleaned <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>SEX), <span class="at">type =</span> <span class="st">"prob"</span>), <span class="co">#use regression model to make SEX predictions from existing DOSE observations, returns probabilities of sex categories (2 cols)</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">observation =</span> mavoglurant_data_cleaned<span class="sc">$</span>SEX) <span class="co">#bind to observed sex observations</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>rocauc <span class="ot">=</span> <span class="fu">roc_auc</span>(predictions, <span class="at">truth =</span> observation, .pred_1) <span class="co">#roc with probabiliy of sex 2 thresholds</span></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">=</span> <span class="fu">roc_curve</span>(predictions, <span class="at">truth =</span> observation, .pred_1) <span class="sc">%&gt;%</span> <span class="co">#plot roc curve</span></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>               <span class="fu">autoplot</span>() <span class="sc">+</span> <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.75</span>, <span class="at">y =</span> <span class="fl">0.25</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"AUC = "</span>, <span class="fu">round</span>(rocauc<span class="sc">$</span>.estimate, <span class="dv">3</span>)))</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a><span class="do">## adjust barplot with accuracy metrics </span></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> plot <span class="sc">+</span> <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">1.7</span>, <span class="at">y =</span> <span class="dv">13</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"accuracy = "</span>, <span class="fu">round</span>(acc<span class="sc">$</span>.estimate, <span class="dv">3</span>)))</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a><span class="co">#save figures</span></span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"metrics_sex_all_reg.png"</span>)</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"roc_sex_all_reg.png"</span>)</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot2) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-metrics-sex-all-reg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/metrics_sex_all_reg.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;10: Barplot of observed Sex 2 counts (orange) against estimated prediction (blue).</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-roc-sex-all-reg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/roc_sex_all_reg.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;11: ROC curve of sensitivity vs specificity in correctly categorizing observations by SEX from all predictors, probability threshold = 0.5 .</figcaption>
</figure>
</div>
</div>
</div>
<p>Including more predictors improves the accuracy of the classification model to 94% (<a href="#fig-metrics-sex-all-reg">Figure&nbsp;10</a>), and the ROC-AUC performance to 0.98 (<a href="#fig-roc-sex-all-reg">Figure&nbsp;11</a>). This model is certainly better at classification than the previous but, once again, fails to support or predict any biological indicator of <code>SEX</code> by the predictors included in the study and may suffer from fitting with too many unnecessary parameters. We did discover, however, the significance of the contributions of different factors to the prediction of <code>SEX</code>, with <code>HT</code> being the most significant predictor (<a href="#tbl-logistic-sex-all">Table&nbsp;7</a>).</p>
</section>
</section>
<section id="model-improvement-assignment" class="level1">
<h1>Model Improvement Assignment</h1>
<p>The code chunk below defines the value of a seed, but does not yet set the seed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>rngseed <span class="ot">=</span> <span class="dv">1234</span> <span class="co">#define the number of our seed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As a last step in processing, we know that the <code>RACE</code> factor variable has some bizarre entries (7 or 88), and we are not particularly curious about asking questions regarding this variable now. So, we are going to remove it from the dataset in the code chunk below. I have also kept the <code>RATE</code> variable until this point, but will be removing it for this part of the assessment as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mavoglurant_data_cleaned <span class="ot">=</span> mavoglurant_data_cleaned <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(RATE,RACE)) <span class="co">#remove variables RATE and RACE from the cleaned dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, our dataset <code>mavoglurant_data_cleaned</code> consist of 120 observations of 6 variables: <code>y</code>, <code>DOSE</code>, <code>AGE</code>, <code>SEX</code>, <code>WT</code>, and <code>HT</code>.</p>
<p>In this section, we will be splitting our data into two subsets: a <em>training</em> set and a <em>test</em> set. The training set will be used to fit our models, while the test set will be used to observe whether the fitted model precisely captures the behavior of the data - that is, how well does it perform when predicting the test data? With so few samples, we would ideally perform cross-validation and estimate model performance on unseen data (separate the dat into k staggered subsets, and run through k epochs of training the model on k-1 subsets and testing on the kth subset each epoch.) But, for the sake of <sub>learning</sub>, we are not going to do that here.</p>
<p>We will be randomly splitting our data 75% into the <code>training</code> set and 25% into the <code>testing</code> set below using the package <code>rsample</code> below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(rngseed)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co">#split the dataset randomly into two sets</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>banana_split <span class="ot">=</span> <span class="fu">initial_split</span>(mavoglurant_data_cleaned, <span class="at">prop =</span> <span class="dv">3</span><span class="sc">/</span><span class="dv">4</span>) <span class="co">#prop refers to the proportion in the training set - 75%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create dataframes for the two sets</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>training <span class="ot">=</span> <span class="fu">training</span>(banana_split)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>testing <span class="ot">=</span> <span class="fu">testing</span>(banana_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="model-fit-assessment" class="level2">
<h2 class="anchored" data-anchor-id="model-fit-assessment">Model Fit Assessment</h2>
<p>Here, we fit two linear models to the continuous outcome, <code>y</code> (as a reminder, <code>y</code> is the sum of <code>DV</code> values for a time series). The first utilises <code>DOSE</code> as a predictor, which we anticipate to have some correlation with the total sum of drug concentration measurments over time; the second model utilizes all predictors. Root Mean Squared Error is the metric used to optimize the model. We compare the fit of each model against the fit of a <em>null model</em>, predicting the mean of the observations without predictor variables.</p>
<section id="fitting-the-models-and-comparing-rmse-metric" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-models-and-comparing-rmse-metric">Fitting the models and comparing RMSE metric</h3>
<p>The following code chunk utilizes the <code>tidymodels</code> framework to fit a linear regression model (method = lm) with <code>DOSE</code> as a predictor of <code>y</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">### fitting a linear model </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># define recipe with recipes package</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>rec_y_DOSE <span class="ot">&lt;-</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">recipe</span>(y <span class="sc">~</span> DOSE, </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> training)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># choose model with parsnip package</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>y_DOSE_reg <span class="ot">=</span> </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="co">#linear regression model</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span> <span class="co">#with lm method</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_mode</span>(<span class="st">"regression"</span>) <span class="co">#mode = regression, mode outcome is numeric</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn this into a workflow with workflows package</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>y_DOSE_reg_WF <span class="ot">=</span> </span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="co">#defining workflow object</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_model</span>(y_DOSE_reg) <span class="sc">%&gt;%</span> <span class="co">#choosing the model for the workflow</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_recipe</span>(rec_y_DOSE) <span class="co">#adding the recipe - which variables for outcome, predictor, any interactions...</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting the model with fit()</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>train_y_DOSE_reg_model <span class="ot">=</span> <span class="fu">fit</span>(y_DOSE_reg_WF, <span class="at">data =</span> training) </span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">=</span> y_DOSE_reg_model <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="do">### saving table results </span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a><span class="co"># save summary tables</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"y_DOSE_reg_training.rds"</span>)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table1, <span class="at">file =</span> summarytable_file)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-y-dose-reg-training" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;8: Linear regression model of y predicted by DOSE on training subset.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">323.06249</td>
<td style="text-align: right;">199.048513</td>
<td style="text-align: right;">1.623034</td>
<td style="text-align: right;">0.1072508</td>
</tr>
<tr class="even">
<td style="text-align: left;">DOSE</td>
<td style="text-align: right;">58.21289</td>
<td style="text-align: right;">5.193797</td>
<td style="text-align: right;">11.208155</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The output of <code>tidymodel</code>’s <code>fit()</code> on our linear regression by <code>lm</code> model provides our estimated parameters (“estimate”, <strong>?@tbl-y-dose-reg_training</strong>), as well as the standard error (<span class="math inline">\(\sigma / \sqrt{n}\)</span>). Below, we use the <code>yardstick</code> package to determine the root mean squared error and correlation coefficient of the linear regression between <code>y</code> and <code>DOSE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate r^2 and RMSE from y_DOSE_reg model </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="do">## make predictions based on real DOSE observations </span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>predictions_y_DOSE_reg_train <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">predictor =</span> training<span class="sc">$</span>DOSE,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">.pred =</span> <span class="fu">predict</span>(train_y_DOSE_reg_model, <span class="at">new_data =</span> training <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>y)), <span class="co">#use regression model to make y predictions from existing DOSE observations</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">observation =</span> training<span class="sc">$</span>y) <span class="co">#bind to observed y observations</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="do">## lets take a look </span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> predictions_y_DOSE_reg_train, <span class="fu">aes</span>(<span class="at">x =</span> predictor, <span class="at">y =</span> observation, <span class="at">color =</span> <span class="fu">factor</span>(predictor))) <span class="sc">+</span> </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_point</span>(<span class="at">data =</span> predictions_y_DOSE_reg_train, <span class="fu">aes</span>(<span class="at">x =</span> predictor, <span class="at">y =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_line</span>(<span class="at">data =</span> predictions_y_DOSE_reg_train, <span class="fu">aes</span>(<span class="at">x =</span> predictor, <span class="at">y =</span> .pred), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>          <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Dose"</span>, <span class="at">y =</span> <span class="st">"DV sum"</span>, <span class="at">title =</span> <span class="st">"Regression model prediction of DV sum by dose"</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="do">## now lets calculate our metrics</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">=</span> yardstick<span class="sc">::</span><span class="fu">metric_set</span>(rmse, rsq)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>table <span class="ot">=</span> <span class="fu">metrics</span>(predictions_y_DOSE_reg_train, <span class="at">truth =</span> observation, <span class="at">estimate =</span> .pred)</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="do">## add rmse and rsq to plot </span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> plot <span class="sc">+</span> <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">y =</span> <span class="dv">4500</span>, <span class="at">x =</span> <span class="fl">32.5</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"RMSE = "</span>, <span class="fu">round</span>(table[<span class="dv">1</span>,<span class="dv">3</span>], <span class="dv">0</span>), <span class="st">"</span><span class="sc">\n</span><span class="st"> rsq = "</span>, <span class="fu">round</span>(table[<span class="dv">2</span>,<span class="dv">3</span>], <span class="dv">3</span>)))</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="co"># saving outputs</span></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"metrics_y_DOSE_reg_training.rds"</span>)</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table, <span class="at">file =</span> summarytable_file)</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"metrics_y_DOSE_reg_training.png"</span>)</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-metrics-y-DOSE-reg-training" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/metrics_y_DOSE_reg_training.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;12: Scatterplot of total DV observed against dose, for training dataset. Dotted line shows linear regression predictions</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-metrics-y-DOSE-reg-training" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;9: RMSE and r-squared for model prediction of DV sum by DOSE on training data.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">702.8077893</td>
</tr>
<tr class="even">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.4507963</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The following code chunk utilizes the <code>tidymodels</code> framework to fit a multiple linear regression model (method = lm) with all variables as a predictor of <code>y</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="do">### fitting a linear model </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># define recipe with recipes package</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>rec_y_multiple <span class="ot">&lt;-</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">recipe</span>(y <span class="sc">~</span> ., </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> training)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># choose model with parsnip package</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>y_multiple_reg <span class="ot">=</span> </span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="co">#linear regression model</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span> <span class="co">#with lm method</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_mode</span>(<span class="st">"regression"</span>) <span class="co">#mode = regression, mode outcome is numeric</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn this into a workflow with workflows package</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>y_multiple_reg_WF <span class="ot">=</span> </span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="co">#defining workflow object</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_model</span>(y_multiple_reg) <span class="sc">%&gt;%</span> <span class="co">#choosing the model for the workflow</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_recipe</span>(rec_y_multiple) <span class="co">#adding the recipe - which variables for outcome, predictor, any interactions...</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting the model with fit()</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>train_y_multiple_reg_model <span class="ot">=</span> <span class="fu">fit</span>(y_multiple_reg_WF, <span class="at">data =</span> training) </span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">=</span> train_y_multiple_reg_model <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a><span class="do">### saving table results </span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="co"># save summary tables</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"y_multiple_reg_training.rds"</span>)</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table1, <span class="at">file =</span> summarytable_file)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-y-multiple-reg-training" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;10: Linear regression model of y predicted by multiple predictors on training subset.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">4396.7716067</td>
<td style="text-align: right;">2169.637335</td>
<td style="text-align: right;">2.0265007</td>
<td style="text-align: right;">0.0458860</td>
</tr>
<tr class="even">
<td style="text-align: left;">DOSE</td>
<td style="text-align: right;">55.3445105</td>
<td style="text-align: right;">5.830979</td>
<td style="text-align: right;">9.4914605</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">-0.4174341</td>
<td style="text-align: right;">9.502942</td>
<td style="text-align: right;">-0.0439268</td>
<td style="text-align: right;">0.9650670</td>
</tr>
<tr class="even">
<td style="text-align: left;">SEX2</td>
<td style="text-align: right;">-568.9967188</td>
<td style="text-align: right;">285.444290</td>
<td style="text-align: right;">-1.9933722</td>
<td style="text-align: right;">0.0494662</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WT</td>
<td style="text-align: right;">-22.6398760</td>
<td style="text-align: right;">7.649873</td>
<td style="text-align: right;">-2.9595100</td>
<td style="text-align: right;">0.0040029</td>
</tr>
<tr class="even">
<td style="text-align: left;">HT</td>
<td style="text-align: right;">-1129.6696482</td>
<td style="text-align: right;">1358.399761</td>
<td style="text-align: right;">-0.8316180</td>
<td style="text-align: right;">0.4079825</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate r^2 and RMSE from y_DOSE_reg model </span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="do">## make predictions based on real DOSE observations </span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>predictions_y_multiple_reg_train <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">predictor_1=</span> training<span class="sc">$</span>DOSE,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">.pred =</span> <span class="fu">predict</span>(train_y_multiple_reg_model, <span class="at">new_data =</span> training <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>y)), <span class="co">#use regression model to make y predictions from existing observations</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">observation =</span> training<span class="sc">$</span>y) <span class="co">#bind to observed y observations</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                                    </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="do">## lets take a look </span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> predictions_y_multiple_reg_train, <span class="fu">aes</span>(<span class="at">x =</span> observation, <span class="at">y =</span> .pred, <span class="at">color =</span> <span class="fu">factor</span>(predictor_1))) <span class="sc">+</span> </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_abline</span>(<span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>          <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Observed"</span>, <span class="at">y =</span> <span class="st">"Predicted"</span>, <span class="at">title =</span> <span class="st">"DV sums observed and predicted by regression"</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="do">## now lets calculate our metrics</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">=</span> yardstick<span class="sc">::</span><span class="fu">metric_set</span>(rmse, rsq)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>table <span class="ot">=</span> <span class="fu">metrics</span>(predictions_y_multiple_reg_train, <span class="at">truth =</span> observation, <span class="at">estimate =</span> .pred)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="do">## add rmse and rsq to plot </span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> plot <span class="sc">+</span> <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">y =</span> <span class="dv">5000</span>, <span class="at">x =</span> <span class="dv">2000</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"RMSE = "</span>, <span class="fu">round</span>(table[<span class="dv">1</span>,<span class="dv">3</span>], <span class="dv">0</span>), <span class="st">"</span><span class="sc">\n</span><span class="st"> rsq = "</span>, <span class="fu">round</span>(table[<span class="dv">2</span>,<span class="dv">3</span>], <span class="dv">3</span>)))</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="co"># saving outputs</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"metrics_y_multiple_reg_training.rds"</span>)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table, <span class="at">file =</span> summarytable_file)</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"figures"</span>, <span class="st">"metrics_y_multiple_reg_training.png"</span>)</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-metrics-y-multiple-reg-training" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/metrics_y_multiple_reg_train.png" class="img-fluid figure-img" width="1844"></p>
<figcaption class="figure-caption">Figure&nbsp;13: Scatterplot of total DV observed against estimated prediction, colored by dose. Diagonal dashed line shows 1:1 corelation</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-metrics-y-multiple-reg-training" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11: RMSE and r-squared for model prediction of DV sum by all predictor variables.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">627.4407539</td>
</tr>
<tr class="even">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.5622706</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We compare the RMSE of the above two regression models to the RMSE of a null model predicting the mean <code>y</code> for each observation without considering <code>DOSE</code>.</p>
<pre class="{yardstick-null-model-training}"><code>#null model 
null_y_reg = null_model() %&gt;%
  set_engine("parsnip") %&gt;%
  set_mode("regression") %&gt;%
  translate()

null_model = fit(null_y_reg, formula = y ~ 1, data = training)

# calculate r^2 and RMSE from y_DOSE_reg model 
## make predictions based on real DOSE observations 
predictions_null_model = data.frame(predictor = training$DOSE,
                                    .pred = predict(null_model, new_data = training %&gt;% select(-y)), #use regression model to make y predictions from existing DOSE observations
                                    observation = training$y) #bind to observed y observations

## lets take a look 
plot = ggplot() + geom_point(data = predictions_null_model, aes(x = predictor, y = observation, color = factor(predictor))) + 
          geom_point(data = predictions_y_DOSE_reg, aes(x = predictor, y = .pred)) + 
          geom_line(data = predictions_y_DOSE_reg, aes(x = predictor, y = .pred), linetype = "dashed") +
          labs(x = "Dose", y = "DV sum", title = "Null model prediction of DV sum, y")
        
## now lets calculate our metrics
metrics = yardstick::metric_set(rmse)
table = metrics(predictions_null_model, truth = observation, estimate = .pred)

## add rmse and rsq to plot 
plot = plot + annotate("text", y = 4500, x = 32.5, label = paste0("RMSE = ", round(table[1,3], 0)))

# saving outputs
summarytable_file = here("fitting-exercise", "tables", "metrics_null_model.rds")
saveRDS(table, file = summarytable_file)

figure_file = here("fitting-exercise", "figures", "metrics_null_model.png")
ggsave(filename = figure_file, plot=plot) </code></pre>
<div class="cell">
<div class="cell-output-display">
<div id="fig-metrics-null-model-training" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/metrics_null_model.png" class="img-fluid figure-img" width="1844"></p>
<figcaption class="figure-caption">Figure&nbsp;14: Scatterplot of sum total DV, y, predicted by null model of training dataset.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-metrics-null-model-training" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;12: RMSE for null model prediction of DV sum from model training.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">948.3526</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Comparing the RMSE values reported in <a href="#tbl-metrics-y-DOSE-reg-training">Table&nbsp;9</a>, <a href="#tbl-metrics-y-multiple-reg-training">Table&nbsp;11</a>, and <strong>?@tbl-metrics-null-model</strong>, we can see that the model with the smallest mean roots squared error is the multiple regression model. However, we can also observe that the <span class="math inline">\(R^2\)</span> value is greater for the single regression model with <code>DOSE</code> as a predictor, which should be taken into consideration when choosing whether the model with a greater number of parameters is truly the “better” model, and not simply the model with the greatest (over?) fit.</p>
<p>Assessing the model performance in a more rigorous way - against unseen data - can improve our understanding of the precision with which the model captures the behavior of the outcome variable based on the predictors. One way to do so is cross-validation.</p>
</section>
<section id="cross--validation-of-three-possible-models" class="level3">
<h3 class="anchored" data-anchor-id="cross--validation-of-three-possible-models">Cross -Validation of Three Possible Models</h3>
<p>In this section, we conduct a 10-fold cross-validation of each model against the training dataset according to the workflow suggest in the <a href="https://www.tidymodels.org/start/resampling/#fit-resamples">Introduction to TidyModels</a>.</p>
<p>The package <code>rsample</code> is used here to create the resampling object - the <em>folds</em> of our data, or indices of random subsets, which will be used in the analysis and assessment of the models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(rngseed) <span class="co">#we are resampling randomly, and should set seed for reproducibility</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co">#here, we define the cross-validation folds from our training data </span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">=</span> rsample<span class="sc">::</span><span class="fu">vfold_cv</span>(training, <span class="at">v =</span> <span class="dv">10</span>) <span class="co">#we would like to define 10 folds</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We would like to define two <code>workflow()</code> objects to bundle the two linear model - formula specifications.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">####### workflow for single regression of y by dose ########</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># choose model with parsnip package</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>y_DOSE_reg <span class="ot">=</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="co">#linear regression model</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span> <span class="co">#with lm method</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_mode</span>(<span class="st">"regression"</span>) <span class="co">#mode = regression, mode outcome is numeric</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn this into a workflow with workflows package</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>y_DOSE_reg_WF <span class="ot">=</span> </span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="co">#defining workflow object</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_model</span>(y_DOSE_reg) <span class="sc">%&gt;%</span> <span class="co">#choosing the model for the workflow</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_formula</span>(y <span class="sc">~</span> DOSE) <span class="sc">%&gt;%</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> training)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="do">##########################################################################</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="do">###### workflow for multiple regression of y by all predictors #######</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="co"># choose model with parsnip package</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>y_multiple_reg <span class="ot">=</span> </span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="co">#linear regression model</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span> <span class="co">#with lm method</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>  parsnip<span class="sc">::</span><span class="fu">set_mode</span>(<span class="st">"regression"</span>) <span class="co">#mode = regression, mode outcome is numeric</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a><span class="co"># we can turn this into a workflow with workflows package</span></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>y_multiple_reg_WF <span class="ot">=</span> </span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="co">#defining workflow object</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_model</span>(y_multiple_reg) <span class="sc">%&gt;%</span> <span class="co">#choosing the model for the workflow</span></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>  workflows<span class="sc">::</span><span class="fu">add_formula</span>(y <span class="sc">~</span> .) <span class="sc">%&gt;%</span></span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> training)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(rngseed)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># CV single regression, y ~ DOSE</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>train_y_dose_rs <span class="ot">=</span> y_DOSE_reg_WF <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  tune<span class="sc">::</span><span class="fu">fit_resamples</span>(folds)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>train_y_dose_CV_metrics <span class="ot">=</span> tune<span class="sc">::</span><span class="fu">collect_metrics</span>(train_y_dose_rs) <span class="co"># extract metrics</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># CV multiple regression, y ~ all</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>train_y_multiple_rs <span class="ot">=</span> y_multiple_reg_WF <span class="sc">%&gt;%</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  tune<span class="sc">::</span><span class="fu">fit_resamples</span>(folds)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>train_y_multiple_CV_metrics <span class="ot">=</span> tune<span class="sc">::</span><span class="fu">collect_metrics</span>(train_y_multiple_rs) <span class="co"># extrac metrics</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="do">## CV on null mdoel doesnt make sense, of course, because the mean of the observations will stay the same. I am simply going to re-fit the null model here to keep the RMSE output in one place :)</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="co">#  refit for null model </span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>null_y_reg <span class="ot">=</span> <span class="fu">null_model</span>() <span class="sc">%&gt;%</span> <span class="co">#fit null model</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"parsnip"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">translate</span>()</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>null_model_metrics <span class="ot">=</span> <span class="fu">fit</span>(null_y_reg, <span class="at">formula =</span> y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> training) <span class="sc">%&gt;%</span> <span class="co">#extract RMSE</span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(<span class="at">new_data =</span> training) <span class="sc">%&gt;%</span> <span class="co">#make predictions based on training data</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.pred) <span class="sc">%&gt;%</span> <span class="co"># isolate predicted values</span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(training<span class="sc">$</span>y) <span class="sc">%&gt;%</span> <span class="co"># bind predictions to training data observations</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">y =</span> <span class="st">"...2"</span>) <span class="sc">%&gt;%</span> <span class="co">#rename column containing observations </span></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rmse</span>(<span class="at">truth =</span> y, <span class="at">estimate =</span> .pred) <span class="co">#calculate</span></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a><span class="co">#create table with CV output for each model</span></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">=</span> <span class="fu">cbind</span>(<span class="st">"Predictor"</span> <span class="ot">=</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"DOSE"</span>, <span class="st">"multiple"</span>), <span class="at">each =</span> <span class="dv">2</span>), <span class="fu">rbind</span>(train_y_dose_CV_metrics, train_y_multiple_CV_metrics)) <span class="co">#table comparing CV of linear regression models</span></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>table2 <span class="ot">=</span> null_model_metrics</span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a><span class="co"># saving outputs</span></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"metrics_CV_models_training.rds"</span>)</span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table1, <span class="at">file =</span> summarytable_file)</span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"tables"</span>, <span class="st">"metrics_null_model_CV.rds"</span>)</span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table2, <span class="at">file =</span> summarytable_file)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-metrics-CV-models-training" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;13: Mean RMSE and <span class="math inline">\(R^2\)</span> from 10-fold cross-validation of the single and multiple linear regression models of y</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 3%">
<col style="width: 14%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">std_err</th>
<th style="text-align: left;">.config</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DOSE</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">690.5397679</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">67.4950937</td>
<td style="text-align: left;">Preprocessor1_Model1</td>
</tr>
<tr class="even">
<td style="text-align: left;">DOSE</td>
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.5117853</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.0592077</td>
<td style="text-align: left;">Preprocessor1_Model1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">multiple</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">645.6909159</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">64.8192708</td>
<td style="text-align: left;">Preprocessor1_Model1</td>
</tr>
<tr class="even">
<td style="text-align: left;">multiple</td>
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.5729141</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.0685670</td>
<td style="text-align: left;">Preprocessor1_Model1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-metrics-null-model-training-CV" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;14: RMSE for null model prediction of DV sum from model training.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">948.3526</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The mean RMSE of the linear regression model with <code>DOSE</code> as a single predictor has actually improved from 702 to 690, though it is still outperformed by the multiple linear regression model, with a mean RMSE of 645. Here, we also see that the <span class="math inline">\(R^2\)</span> value of the multiple regression model has improved and also demonstrates a greater fit of the model than the single regression model (though only slightly).</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>