<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Cora Hirst">

<title>Cora Hirst Data Analysis Portfolio - cdcdata-exercise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Cora Hirst Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../aboutme.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../../starter-analysis-exercise/products/report/starter-analysis-report.html" rel="" target="">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../coding-exercise/coding-exercise.html" rel="" target="">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../presentation-exercise/presentation-exercise.html" rel="" target="">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tidytuesday-exercise/tidytuesday-exercise.html" rel="" target="">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../data-exercise/code/data-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../cdc-exercise/code/cdcdata-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Analysis Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/CoraHirst/corahirst-MADA-portfolio" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">cdcdata-exercise</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Cora Hirst </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ggplot2")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("dplyr")</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("here")</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/chirst/Desktop/Git/corahirst-MADA-portfolio</code></pre>
</div>
</div>
<section id="whats-the-dataset" class="level1">
<h1>What’s the Dataset?</h1>
<p>The following is a dataset containing measurements of morbitiy, mortality, and viral titre for 717 ferrets inoculated with 125 different Influenza A virus strains. Each observation contains data on a single ferret - thus, thre are 717 observations.</p>
<p>Viral titres were measured from nasal washes (NW) every-other day after incolution, and are given in columns <code>d#_inoc</code>, where <code>d#</code> indicates the number of days elapsed since inoculation. <code>units</code> indicates whether titres are reported in PFU or EID50 (tirated in cells or eggs!).</p>
<p>The <code>virus</code> column contains the unique identifier for the virus used to inoculate the ferret. Column <code>lethal</code> contains binary information, indicating whether the ferret survived (<code>FALSE</code>) the 14-day period or was humanely euthanized once titres reached humane endpoint criteria (<code>TRUE</code>).</p>
<p><code>HPAI</code> inicates whether the virus has been classified as highly pathogenic avian influenza (<code>TRUE</code>) or is either low pathogenic avian influenza or non-avian (<code>FALSE</code>). <code>HPAI_MBAA</code> indicates whether the virus, if HPAI, has a multibasic amino acid cleavage site.</p>
<p>The <code>HA</code> and <code>NA.</code> columns depict the subtypes of hemaglutinin or neuraminidase (H#N#) of the inoculated virus.</p>
<p>The <code>wt_loss</code> and <code>wt_loss_day</code> columns indicate the maximum percentage weight loss the ferret experienced, and the day at which this maximum weight loss was reached.</p>
<p>Laslty, <code>temp</code> and <code>temp_day</code> report the maximum temperature experienced by the ferret, and the day that temperature was reached.</p>
<p>There are a few other columns in the dataset I will <em>not</em> be considering for the purpose of this exercise, including information about respiratory transmission, from where the virus was isolated, etc.</p>
<p>The public dataset was obtained from the CDC’s National Center for Immunization and Respiratory Diseases, <a href="https://data.cdc.gov/National-Center-for-Immunization-and-Respiratory-D/An-aggregated-dataset-of-serially-collected-influe/cr56-k9wj/about_data">here</a>.</p>
</section>
<section id="data-processing" class="level1">
<h1>Data Processing</h1>
<p>The dataset is loaded, viewed, and processed accordingly in the following section.</p>
<section id="loading-the-data-and-selecting-variables-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-data-and-selecting-variables-of-interest">Loading the data and selecting variables of interest</h2>
<p>The following code chunk solely loads the data and visualizes all 28 variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load dataset</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>ferret_IAV_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"cdc-exercise"</span>, <span class="st">"data"</span>, <span class="st">"IAV_morbidity_and_titer_measurements_ferrets.csv"</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># view dataset </span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ferret_IAV_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   717 obs. of  28 variables:
 $ Ferret     : chr  "F1" "F2" "F3" "F4" ...
 $ Virus      : chr  "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" ...
 $ units      : chr  "EID" "EID" "EID" "EID" ...
 $ expt       : chr  "path" "path" "path" "path" ...
 $ lethal     : chr  "false" "false" "false" "false" ...
 $ lethal_day : int  0 0 0 0 0 0 0 0 0 0 ...
 $ NW_typical : chr  "true" "true" "true" "true" ...
 $ RD_trans   : chr  NA NA NA NA ...
 $ HPAI       : chr  "false" "false" "false" "false" ...
 $ HPAI_MBAA  : chr  "false" "false" "false" "false" ...
 $ HA         : chr  "H7" "H7" "H7" "H7" ...
 $ NA.        : chr  "N2" "N2" "N2" "N2" ...
 $ Origin     : chr  "avian" "avian" "avian" "avian" ...
 $ wt_loss    : num  6.7 11.8 15.4 5.9 7.9 6.1 3.5 22.5 15 14.9 ...
 $ wt_loss_day: int  7 4 6 11 5 9 11 7 7 8 ...
 $ temp       : num  0.5 0.9 2 1 1 0.5 0.5 1.1 1.1 1 ...
 $ temp_day   : int  4 7 8 9 3 3 7 7 7 1 ...
 $ temp_5     : num  0.5 0.7 1.8 0.3 1 0.5 0.3 0.1 0.6 1 ...
 $ temp_5_day : int  4 2 2 3 3 3 1 3 3 1 ...
 $ d1_inoc    : num  6.5 5.5 6.25 6.75 6.25 7.25 5.75 5.75 4.75 6.5 ...
 $ d2_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d3_inoc    : num  4.5 6.5 5.5 6.75 6.5 6.75 5.75 5.5 3.75 5.25 ...
 $ d4_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d5_inoc    : num  4.75 4.75 5.75 5.75 4.75 4.5 5.75 5.5 5.25 6.5 ...
 $ d6_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d7_inoc    : num  1.75 1.5 1.5 3.25 1.5 1.5 1.5 2.25 1.5 3.25 ...
 $ d8_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d9_inoc    : num  1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 ...</code></pre>
</div>
</div>
<p>Now, I would like to subset the dataset for only the variables of interest:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select variables from dataset</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ferret_IAV_data <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="st">"expt"</span>, <span class="st">"NW_typical"</span>, <span class="st">"RD_trans"</span>, <span class="st">"Origin"</span>, <span class="st">"temp_5"</span>, <span class="st">"temp_5_day"</span>))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># view pruned dataset</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ferret_IAV_data) <span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   717 obs. of  22 variables:
 $ Ferret     : chr  "F1" "F2" "F3" "F4" ...
 $ Virus      : chr  "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" ...
 $ units      : chr  "EID" "EID" "EID" "EID" ...
 $ lethal     : chr  "false" "false" "false" "false" ...
 $ lethal_day : int  0 0 0 0 0 0 0 0 0 0 ...
 $ HPAI       : chr  "false" "false" "false" "false" ...
 $ HPAI_MBAA  : chr  "false" "false" "false" "false" ...
 $ HA         : chr  "H7" "H7" "H7" "H7" ...
 $ NA.        : chr  "N2" "N2" "N2" "N2" ...
 $ wt_loss    : num  6.7 11.8 15.4 5.9 7.9 6.1 3.5 22.5 15 14.9 ...
 $ wt_loss_day: int  7 4 6 11 5 9 11 7 7 8 ...
 $ temp       : num  0.5 0.9 2 1 1 0.5 0.5 1.1 1.1 1 ...
 $ temp_day   : int  4 7 8 9 3 3 7 7 7 1 ...
 $ d1_inoc    : num  6.5 5.5 6.25 6.75 6.25 7.25 5.75 5.75 4.75 6.5 ...
 $ d2_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d3_inoc    : num  4.5 6.5 5.5 6.75 6.5 6.75 5.75 5.5 3.75 5.25 ...
 $ d4_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d5_inoc    : num  4.75 4.75 5.75 5.75 4.75 4.5 5.75 5.5 5.25 6.5 ...
 $ d6_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d7_inoc    : num  1.75 1.5 1.5 3.25 1.5 1.5 1.5 2.25 1.5 3.25 ...
 $ d8_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d9_inoc    : num  1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ferret_IAV_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Ferret             Virus              units              lethal         
 Length:717         Length:717         Length:717         Length:717        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
   lethal_day         HPAI            HPAI_MBAA              HA           
 Min.   : 0.000   Length:717         Length:717         Length:717        
 1st Qu.: 0.000   Class :character   Class :character   Class :character  
 Median : 0.000   Mode  :character   Mode  :character   Mode  :character  
 Mean   : 1.013                                                           
 3rd Qu.: 0.000                                                           
 Max.   :13.000                                                           
                                                                          
     NA.               wt_loss        wt_loss_day          temp      
 Length:717         Min.   : 0.000   Min.   : 0.000   Min.   :0.000  
 Class :character   1st Qu.: 4.800   1st Qu.: 4.000   1st Qu.:1.000  
 Mode  :character   Median : 9.200   Median : 7.000   Median :1.600  
                    Mean   : 9.869   Mean   : 6.424   Mean   :1.596  
                    3rd Qu.:14.400   3rd Qu.: 9.000   3rd Qu.:2.200  
                    Max.   :27.500   Max.   :14.000   Max.   :4.000  
                    NA's   :2                         NA's   :4      
    temp_day       d1_inoc         d2_inoc         d3_inoc         d4_inoc     
 Min.   : 0.0   Min.   :1.000   Min.   :3.500   Min.   :1.980   Min.   :1.980  
 1st Qu.: 1.0   1st Qu.:4.800   1st Qu.:5.500   1st Qu.:4.500   1st Qu.:4.255  
 Median : 2.0   Median :5.780   Median :6.155   Median :5.320   Median :5.250  
 Mean   : 3.1   Mean   :5.811   Mean   :5.950   Mean   :5.284   Mean   :5.046  
 3rd Qu.: 4.0   3rd Qu.:6.750   3rd Qu.:6.500   3rd Qu.:6.250   3rd Qu.:5.750  
 Max.   :14.0   Max.   :9.250   Max.   :8.750   Max.   :8.750   Max.   :7.500  
                NA's   :110     NA's   :607     NA's   :110     NA's   :607    
    d5_inoc         d6_inoc         d7_inoc         d8_inoc     
 Min.   :1.500   Min.   :1.500   Min.   :1.000   Min.   :1.000  
 1st Qu.:4.460   1st Qu.:3.250   1st Qu.:1.000   1st Qu.:1.500  
 Median :5.100   Median :4.500   Median :1.500   Median :1.500  
 Mean   :5.042   Mean   :4.195   Mean   :1.986   Mean   :1.573  
 3rd Qu.:5.750   3rd Qu.:5.250   3rd Qu.:2.500   3rd Qu.:1.500  
 Max.   :9.500   Max.   :6.750   Max.   :7.000   Max.   :3.500  
 NA's   :116     NA's   :615     NA's   :142     NA's   :626    
    d9_inoc     
 Min.   :1.000  
 1st Qu.:1.000  
 Median :1.500  
 Mean   :1.327  
 3rd Qu.:1.500  
 Max.   :4.750  
 NA's   :169    </code></pre>
</div>
</div>
</section>
<section id="processing" class="level2">
<h2 class="anchored" data-anchor-id="processing">Processing</h2>
<p>All titre variables (<code>d#_inoc</code>), <code>wt_loss</code>, and <code>temp</code> are numeric, as they should be. Similarly, the ID variables <code>Ferret</code> and <code>Virus</code> are similarly loaded correctly as character. Lastly, any time variable counting days post inoculation, <code>lethal_day</code>, <code>wt_loss_day</code>, and <code>temp_day</code> are integers, as days are counted discretely.</p>
<p><code>HA</code> and <code>NA.</code>, referring to the head and neuraminidase subtypes of the virus used in each observation, were loaded as character. While they are character variables inherently, different virus can have different combinations of HA and NA, and can be grouped by either. The type of units titres were measured with, <code>units</code>, is also a categorical variable, as observations can contain one of two values, “EID” or “PFU”. Thus, we can treat <code>units</code>, <code>HA</code>, and <code>NA.</code> as categorical, and <em>factor them.</em></p>
<p>All binary variables - <code>lethal</code>, <code>HPAI</code>, and <code>HPAI_MBAA</code> - are loaded as characters and not as logical. We can fix that, too.</p>
<p>The following code chunk factors the categorical variables and replaces binary character variables with logical values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first, lets factor categorical variables</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ferret_IAV_data <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"units"</span> <span class="ot">=</span> <span class="fu">factor</span>(units), <span class="st">"HA"</span> <span class="ot">=</span> <span class="fu">factor</span>(HA), <span class="st">"NA."</span> <span class="ot">=</span> <span class="fu">factor</span>(NA.)) </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># now, lets replace binary character variables with logical values</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>ferret_IAV_data <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"lethal"</span> <span class="ot">=</span> <span class="fu">case_when</span>(lethal <span class="sc">==</span> <span class="st">"true"</span> <span class="sc">~</span> <span class="cn">TRUE</span>, lethal <span class="sc">==</span> <span class="st">"false"</span> <span class="sc">~</span> <span class="cn">FALSE</span>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>         <span class="st">"HPAI"</span> <span class="ot">=</span> <span class="fu">case_when</span>(HPAI <span class="sc">==</span> <span class="st">"true"</span> <span class="sc">~</span> <span class="cn">TRUE</span>, HPAI <span class="sc">==</span> <span class="st">"false"</span> <span class="sc">~</span> <span class="cn">FALSE</span>), </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>         <span class="st">"HPAI_MBAA"</span> <span class="ot">=</span> <span class="fu">case_when</span>(HPAI_MBAA <span class="sc">==</span> <span class="st">"true"</span> <span class="sc">~</span> <span class="cn">TRUE</span>, HPAI_MBAA <span class="sc">==</span> <span class="st">"false"</span> <span class="sc">~</span> <span class="cn">FALSE</span>))</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># let's check that worked!</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ferret_IAV_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   717 obs. of  22 variables:
 $ Ferret     : chr  "F1" "F2" "F3" "F4" ...
 $ Virus      : chr  "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" ...
 $ units      : Factor w/ 2 levels "EID","PFU": 1 1 1 1 1 1 1 1 1 1 ...
 $ lethal     : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ lethal_day : int  0 0 0 0 0 0 0 0 0 0 ...
 $ HPAI       : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ HPAI_MBAA  : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ HA         : Factor w/ 6 levels "H1","H2","H3",..: 5 5 5 5 5 5 5 5 5 5 ...
 $ NA.        : Factor w/ 7 levels "N1","N2","N3",..: 2 2 2 2 2 2 2 2 2 5 ...
 $ wt_loss    : num  6.7 11.8 15.4 5.9 7.9 6.1 3.5 22.5 15 14.9 ...
 $ wt_loss_day: int  7 4 6 11 5 9 11 7 7 8 ...
 $ temp       : num  0.5 0.9 2 1 1 0.5 0.5 1.1 1.1 1 ...
 $ temp_day   : int  4 7 8 9 3 3 7 7 7 1 ...
 $ d1_inoc    : num  6.5 5.5 6.25 6.75 6.25 7.25 5.75 5.75 4.75 6.5 ...
 $ d2_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d3_inoc    : num  4.5 6.5 5.5 6.75 6.5 6.75 5.75 5.5 3.75 5.25 ...
 $ d4_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d5_inoc    : num  4.75 4.75 5.75 5.75 4.75 4.5 5.75 5.5 5.25 6.5 ...
 $ d6_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d7_inoc    : num  1.75 1.5 1.5 3.25 1.5 1.5 1.5 2.25 1.5 3.25 ...
 $ d8_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d9_inoc    : num  1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ferret_IAV_data) <span class="co">#logicals are logicals and factors are factors, both with count information</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Ferret             Virus           units       lethal       
 Length:717         Length:717         EID:438   Mode :logical  
 Class :character   Class :character   PFU:279   FALSE:615      
 Mode  :character   Mode  :character             TRUE :102      
                                                                
                                                                
                                                                
                                                                
   lethal_day        HPAI         HPAI_MBAA        HA      NA.     
 Min.   : 0.000   Mode :logical   Mode :logical   H1:213   N1:315  
 1st Qu.: 0.000   FALSE:510       FALSE:522       H2: 51   N2:260  
 Median : 0.000   TRUE :207       TRUE :195       H3:123   N3: 36  
 Mean   : 1.013                                   H5:156   N6:  9  
 3rd Qu.: 0.000                                   H7:149   N7: 24  
 Max.   :13.000                                   H9: 25   N8:  9  
                                                           N9: 64  
    wt_loss        wt_loss_day          temp          temp_day   
 Min.   : 0.000   Min.   : 0.000   Min.   :0.000   Min.   : 0.0  
 1st Qu.: 4.800   1st Qu.: 4.000   1st Qu.:1.000   1st Qu.: 1.0  
 Median : 9.200   Median : 7.000   Median :1.600   Median : 2.0  
 Mean   : 9.869   Mean   : 6.424   Mean   :1.596   Mean   : 3.1  
 3rd Qu.:14.400   3rd Qu.: 9.000   3rd Qu.:2.200   3rd Qu.: 4.0  
 Max.   :27.500   Max.   :14.000   Max.   :4.000   Max.   :14.0  
 NA's   :2                         NA's   :4                     
    d1_inoc         d2_inoc         d3_inoc         d4_inoc     
 Min.   :1.000   Min.   :3.500   Min.   :1.980   Min.   :1.980  
 1st Qu.:4.800   1st Qu.:5.500   1st Qu.:4.500   1st Qu.:4.255  
 Median :5.780   Median :6.155   Median :5.320   Median :5.250  
 Mean   :5.811   Mean   :5.950   Mean   :5.284   Mean   :5.046  
 3rd Qu.:6.750   3rd Qu.:6.500   3rd Qu.:6.250   3rd Qu.:5.750  
 Max.   :9.250   Max.   :8.750   Max.   :8.750   Max.   :7.500  
 NA's   :110     NA's   :607     NA's   :110     NA's   :607    
    d5_inoc         d6_inoc         d7_inoc         d8_inoc     
 Min.   :1.500   Min.   :1.500   Min.   :1.000   Min.   :1.000  
 1st Qu.:4.460   1st Qu.:3.250   1st Qu.:1.000   1st Qu.:1.500  
 Median :5.100   Median :4.500   Median :1.500   Median :1.500  
 Mean   :5.042   Mean   :4.195   Mean   :1.986   Mean   :1.573  
 3rd Qu.:5.750   3rd Qu.:5.250   3rd Qu.:2.500   3rd Qu.:1.500  
 Max.   :9.500   Max.   :6.750   Max.   :7.000   Max.   :3.500  
 NA's   :116     NA's   :615     NA's   :142     NA's   :626    
    d9_inoc     
 Min.   :1.000  
 1st Qu.:1.000  
 Median :1.500  
 Mean   :1.327  
 3rd Qu.:1.500  
 Max.   :4.750  
 NA's   :169    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#note that we could have accomplished both in the same "pipe" - I've separated them here to make it clear what manipulation is being preformed on which columns :)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s think about our <code>units</code> variable. “PFU” and “EID50” are both measurements of virus titres, but come from different titration methods - essentially, this means that they cannot be compared.</p>
<p>I’d like to make some correlations between virus titres and other variables included in the dataset. I can’t do that with a mixture of titration methods! So, I am only going to include observations where viral titres were measured via the titration method with the greatest number of observations.</p>
<p>In the following code chunk, I determine which titration <code>unit</code>, “PFU” or “EID”, has the greatest number of observations. Then, I am going to filter my dataset to only include observations where titres are measured with that method. I’ll keep that variable around, though there will only be observations for one factor level, just as a reminder which units the titres are measured in.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># which factor level of units has the greatest number of observations? </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>units.counts <span class="ot">=</span> (<span class="fu">summary</span>(ferret_IAV_data<span class="sc">$</span>units)) <span class="co">#a named vector of counts of the number of observations for each level of variable "units"</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>which.units.max <span class="ot">=</span> <span class="fu">names</span>(units.counts)[<span class="fu">which.max</span>(units.counts)] <span class="co">#the name of the level of variable "units" with the greatest number of observations</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># filtering for observations with titres given in units which.units.max </span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>ferret_IAV_data <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(units <span class="sc">==</span> which.units.max)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># let's check that worked!</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ferret_IAV_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   438 obs. of  22 variables:
 $ Ferret     : chr  "F1" "F2" "F3" "F4" ...
 $ Virus      : chr  "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" ...
 $ units      : Factor w/ 2 levels "EID","PFU": 1 1 1 1 1 1 1 1 1 1 ...
 $ lethal     : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ lethal_day : int  0 0 0 0 0 0 0 0 0 0 ...
 $ HPAI       : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ HPAI_MBAA  : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ HA         : Factor w/ 6 levels "H1","H2","H3",..: 5 5 5 5 5 5 5 5 5 5 ...
 $ NA.        : Factor w/ 7 levels "N1","N2","N3",..: 2 2 2 2 2 2 2 2 2 5 ...
 $ wt_loss    : num  6.7 11.8 15.4 5.9 7.9 6.1 3.5 22.5 15 14.9 ...
 $ wt_loss_day: int  7 4 6 11 5 9 11 7 7 8 ...
 $ temp       : num  0.5 0.9 2 1 1 0.5 0.5 1.1 1.1 1 ...
 $ temp_day   : int  4 7 8 9 3 3 7 7 7 1 ...
 $ d1_inoc    : num  6.5 5.5 6.25 6.75 6.25 7.25 5.75 5.75 4.75 6.5 ...
 $ d2_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d3_inoc    : num  4.5 6.5 5.5 6.75 6.5 6.75 5.75 5.5 3.75 5.25 ...
 $ d4_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d5_inoc    : num  4.75 4.75 5.75 5.75 4.75 4.5 5.75 5.5 5.25 6.5 ...
 $ d6_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d7_inoc    : num  1.75 1.5 1.5 3.25 1.5 1.5 1.5 2.25 1.5 3.25 ...
 $ d8_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d9_inoc    : num  1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ferret_IAV_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Ferret             Virus           units       lethal       
 Length:438         Length:438         EID:438   Mode :logical  
 Class :character   Class :character   PFU:  0   FALSE:348      
 Mode  :character   Mode  :character             TRUE :90       
                                                                
                                                                
                                                                
                                                                
   lethal_day        HPAI         HPAI_MBAA        HA      NA.     
 Min.   : 0.000   Mode :logical   Mode :logical   H1: 73   N1:214  
 1st Qu.: 0.000   FALSE:231       FALSE:243       H2: 51   N2:119  
 Median : 0.000   TRUE :207       TRUE :195       H3: 25   N3: 36  
 Mean   : 1.429                                   H5:156   N6:  9  
 3rd Qu.: 0.000                                   H7:112   N7: 24  
 Max.   :13.000                                   H9: 21   N8:  9  
                                                           N9: 27  
    wt_loss        wt_loss_day          temp          temp_day     
 Min.   : 0.000   Min.   : 0.000   Min.   :0.000   Min.   : 0.000  
 1st Qu.: 4.200   1st Qu.: 4.000   1st Qu.:1.100   1st Qu.: 1.000  
 Median : 9.000   Median : 7.000   Median :1.700   Median : 2.000  
 Mean   : 9.803   Mean   : 6.194   Mean   :1.694   Mean   : 3.292  
 3rd Qu.:15.000   3rd Qu.: 8.000   3rd Qu.:2.300   3rd Qu.: 5.000  
 Max.   :27.200   Max.   :14.000   Max.   :4.000   Max.   :12.000  
 NA's   :1                         NA's   :2                       
    d1_inoc         d2_inoc         d3_inoc         d4_inoc     
 Min.   :1.980   Min.   :3.500   Min.   :1.980   Min.   :1.980  
 1st Qu.:4.500   1st Qu.:5.312   1st Qu.:4.750   1st Qu.:4.319  
 Median :5.500   Median :5.750   Median :5.750   Median :5.500  
 Mean   :5.518   Mean   :5.832   Mean   :5.492   Mean   :5.112  
 3rd Qu.:6.500   3rd Qu.:6.500   3rd Qu.:6.500   3rd Qu.:6.125  
 Max.   :9.250   Max.   :8.750   Max.   :8.750   Max.   :7.500  
 NA's   :94      NA's   :344     NA's   :94      NA's   :344    
    d5_inoc         d6_inoc         d7_inoc        d8_inoc         d9_inoc     
 Min.   :1.500   Min.   :1.500   Min.   :1.50   Min.   :1.500   Min.   :1.500  
 1st Qu.:4.500   1st Qu.:3.250   1st Qu.:1.50   1st Qu.:1.500   1st Qu.:1.500  
 Median :5.250   Median :4.500   Median :1.98   Median :1.500   Median :1.500  
 Mean   :5.236   Mean   :4.142   Mean   :2.44   Mean   :1.583   Mean   :1.565  
 3rd Qu.:6.250   3rd Qu.:5.250   3rd Qu.:3.25   3rd Qu.:1.500   3rd Qu.:1.500  
 Max.   :9.500   Max.   :6.750   Max.   :7.00   Max.   :3.500   Max.   :4.750  
 NA's   :99      NA's   :352     NA's   :122    NA's   :363     NA's   :148    </code></pre>
</div>
</div>
<p>It seems that the majority of titres were measured in EID units (meaning that titrations were done in eggs!), so only observations where titres were measured in EID are being included in the processed dataset. Please note that all observations and variables remain in the file “cdc-exercise/data/IAV_morbidity_and_titer_measurements_ferrets.csv”, so we can reconduct this processing and analysis <em>excluding</em> all observations measured in EID instead, if we want!</p>
<p>At this point, we should have 438 observations remaining.</p>
<p>Lastly, looking at the column <code>lethal_day</code>, ferrets that survived there infection are given a 0 for lethal_day. But that will skew our data quite a bit toward early lethality! So, I want to replace all “0” values for <code>lethal_day</code> with “NA”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ferret_IAV_data <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lethal_day =</span> <span class="fu">case_when</span>(lethal_day <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="cn">NA</span>, <span class="at">.default =</span> lethal_day))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="preliminary-analysis" class="level1">
<h1>Preliminary Analysis</h1>
<p>Now, I have a dataset containing:</p>
<ul>
<li>The ID of the <code>Ferret</code> inocultated, and the ID of the <code>Virus</code> used to inoculated;</li>
<li>whether the infection was <code>lethal</code>;</li>
<li>if the infection was lethal, when the ferret died (<code>lethal_day</code>);</li>
<li>whether the virus is a highly virulant avian <code>HPAI</code>;</li>
<li>if the virus is highly virulent <code>HPAI</code>, whether it has a multi-basic amino acid cleavage site at HA, or an <code>HPAI_MBAA</code>;</li>
<li>the identity of the virus’s <code>HA</code> and <code>NA</code> subtypes;</li>
<li>the maximum percentage <code>wt_loss</code> of the ferret and which day this maximum was measured (<code>wt_loss_day</code>);</li>
<li>the maximum temperature <code>temp</code> of the ferret and which day this maximum was measured (<code>temp_day</code>), and</li>
<li>a time series of viral titres, given in columns <code>d1_inoc</code> through <code>d9_inoc</code></li>
</ul>
<p>This is a lot of information! Yay! What would we like to know about each of these variables?</p>
<p>I’d like to know the proportion of ferrets that died after inoculation, and of these, the distribution in how long they survived:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">data =</span> ferret_IAV_data, <span class="fu">aes</span>(<span class="at">x =</span> lethal, <span class="at">y =</span> (..count..)<span class="sc">/</span><span class="fu">sum</span>(..count..))) <span class="sc">+</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">data =</span> ferret_IAV_data, <span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> lethal, <span class="at">label =</span> ..count.., <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">nrow</span>(ferret_IAV_data)))) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"ferret died"</span>, <span class="at">y =</span> <span class="st">"frequency"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>plot1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/exploration-lethality-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(lethal <span class="sc">==</span> T) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> lethal_day)) <span class="sc">+</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="fl">7.5</span>, <span class="at">label =</span> <span class="fu">paste</span>(<span class="fu">sum</span>(ferret_IAV_data<span class="sc">$</span>lethal<span class="sc">==</span><span class="cn">TRUE</span>), <span class="st">"lethal observations"</span>)) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"days survived"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>plot2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/exploration-lethality-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I’d also like to know how many strains are categorized as highly virulent/pathogenic, and how many ferrets died when infected with them:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>table <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"HPAI"</span>, <span class="st">"lethal"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HPAI) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(lethal)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"HPAI"</span>, <span class="st">"lethal"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(lethal <span class="sc">==</span> T) <span class="sc">%&gt;%</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> HPAI, <span class="at">y =</span> (..count..)<span class="sc">/</span><span class="fu">sum</span>(..count..))) <span class="sc">+</span> </span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> HPAI, <span class="at">label =</span> <span class="fu">paste</span>(..count.., <span class="st">"observations"</span>), <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="fu">sum</span>(ferret_IAV_data<span class="sc">$</span>lethal<span class="sc">==</span>T)))) <span class="sc">+</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"highly pathogenic HPAI"</span>, <span class="at">y =</span> <span class="st">"frequency"</span>, <span class="at">title =</span> <span class="st">"Percentage of dead ferrets infected with highly pathogenic HPAI"</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>plot3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/exploration-pathogenicity-mortality-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"HPAI"</span>, <span class="st">"lethal"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(HPAI <span class="sc">==</span> T) <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> lethal, <span class="at">y =</span> (..count..)<span class="sc">/</span><span class="fu">sum</span>(..count..))) <span class="sc">+</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> lethal, <span class="at">label =</span> <span class="fu">paste</span>(..count.., <span class="st">"observations"</span>), <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">sum</span>(ferret_IAV_data<span class="sc">$</span>HPAI<span class="sc">==</span>T)))) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"ferret died"</span>, <span class="at">y =</span> <span class="st">"frequency"</span>, <span class="at">title =</span> <span class="st">"Percentage ferrets infected with highly pathogenic HPAI that died"</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>plot4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/exploration-pathogenicity-mortality-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>How many highly virulent strains have the weird molecular thing (multi-basic cleavage site on HA, I mean) going on? How many lethal strains have the weird molecular thing going on?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter for HPAI and HPAI_MBAA</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>plot5 <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"HPAI"</span>, <span class="st">"HPAI_MBAA"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(HPAI <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="co"># only include observations for which HPAI is TRUE</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> HPAI_MBAA, <span class="at">y =</span> ..count..<span class="sc">/</span><span class="fu">sum</span>(..count..))) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> HPAI_MBAA, <span class="at">label =</span> <span class="fu">paste</span>(..count.., <span class="st">"observations"</span>), <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">sum</span>(ferret_IAV_data<span class="sc">$</span>HPAI<span class="sc">==</span>T)))) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Has multi-basic amino acid cleavage site"</span>, <span class="at">y =</span> <span class="st">"proportion"</span>, <span class="at">title =</span> <span class="st">"proportion of highly pathogenic HPAI with MBAA"</span> )</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>plot5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/pathogenicity-chemistry-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Knowing that most highly pathogenic HPAI have MBAA, lets see if the HPAI that killed the ferrets were MBAA +</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>plot6 <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"lethal"</span>, <span class="st">"HPAI"</span>, <span class="st">"HPAI_MBAA"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(HPAI <span class="sc">==</span> <span class="cn">TRUE</span>, lethal <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="co"># only observations that have HPAI and died (89 observations, according to plot4)</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> HPAI_MBAA, <span class="at">y =</span> ..count..<span class="sc">/</span><span class="fu">sum</span>(..count..))) <span class="sc">+</span> <span class="co">#of these obs, proportion w and without MBAA</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> HPAI_MBAA, <span class="at">label =</span> <span class="fu">paste</span>(..count.., <span class="st">"observations"</span>), <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">sum</span>(ferret_IAV_data<span class="sc">$</span>HPAI<span class="sc">==</span>T)))) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Has multi-basic amino acid cleavage site"</span>, <span class="at">y =</span> <span class="st">"proportion"</span>, <span class="at">title =</span> <span class="st">"proportion of lethal, highly pathogenic HPAI with MBAA"</span> )</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>plot6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/pathogenicity-chemistry-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># and just to be good, lets see the proportion of HPAI that DIDN'T kill the ferrets that are MBAA - </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>plot7 <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"lethal"</span>, <span class="st">"HPAI"</span>, <span class="st">"HPAI_MBAA"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(HPAI <span class="sc">==</span> <span class="cn">TRUE</span>, lethal <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="co"># only observations that have HPAI and DIDNT die (118 observations, according to plot4)</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> HPAI_MBAA, <span class="at">y =</span> ..count..<span class="sc">/</span><span class="fu">sum</span>(..count..))) <span class="sc">+</span> <span class="co">#of these obs, proportion w and without MBAA</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> HPAI_MBAA, <span class="at">label =</span> <span class="fu">paste</span>(..count.., <span class="st">"observations"</span>), <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">sum</span>(ferret_IAV_data<span class="sc">$</span>HPAI<span class="sc">==</span>T)))) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Has multi-basic amino acid cleavage site"</span>, <span class="at">y =</span> <span class="st">"proportion"</span>, <span class="at">title =</span> <span class="st">"proportion of NON-lethal, highly pathogenic HPAI with MBAA"</span> )</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>plot7</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/pathogenicity-chemistry-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>So MBAA might make a highly pathogenic MBAA slightly more lethal, but hardly. That’s why we do this sort of thing!</p>
<p>Okay, now that that is over -</p>
<ol type="1">
<li>Diversity of NA and HA; how many combinations, and representation of each combination? Which combos incude highly pathogenic HPAI?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we will add a variable with the subtype of IAV</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>ferret_IAV_data <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">subtype =</span> <span class="fu">as.factor</span>(<span class="fu">paste0</span>(HA,NA.))) <span class="co">#subtype nomenclature is H#N#</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># lets see a bar plot of subtypes</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>plot8 <span class="ot">=</span> ferret_IAV_data <span class="sc">%&gt;%</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> subtype, <span class="at">y =</span> ..count..<span class="sc">/</span><span class="fu">sum</span>(..count..), <span class="at">fill =</span> HPAI)) <span class="sc">+</span>  <span class="co">#I wanted to add a little color for no reason ;)</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">2.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> subtype, <span class="at">label =</span> ..count.., <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">length</span>(ferret_IAV_data<span class="sc">$</span>subtype)))) <span class="sc">+</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"subtype"</span>, <span class="at">y =</span> <span class="st">"proportion"</span>, <span class="at">title =</span> <span class="st">"proportion of inoculated influenza A subtypes"</span> )</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>plot8</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/HA-NA-Summary-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="2" type="1">
<li>Overall, how much weight loss? Stratified by whether they died?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#lets see what a scatterplot of max percentage weight loss by day of max weight loss looks like</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>plot9 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">data =</span> ferret_IAV_data, <span class="fu">aes</span>(<span class="at">x =</span> wt_loss_day, <span class="at">y =</span> wt_loss, <span class="at">group =</span> wt_loss_day)) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> ferret_IAV_data, <span class="fu">aes</span>(<span class="at">x =</span> wt_loss_day, <span class="at">y =</span> wt_loss, <span class="at">col =</span> lethal), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>( <span class="at">x =</span> <span class="st">"day of maximum percentage weight loss"</span>, <span class="at">y =</span> <span class="st">"percentage weight loss"</span>, <span class="at">title =</span> <span class="st">"max percentage weight loss by day"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>plot9</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/wt-loss-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="3" type="1">
<li>Diversity in temperatures for dead/not dead? highly virulent vs not?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#lets see what a scatterplot of max percentage weight loss by day of max weight loss looks like</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>plot10 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">data =</span> ferret_IAV_data, <span class="fu">aes</span>(<span class="at">x =</span> temp_day, <span class="at">y =</span> temp, <span class="at">group =</span> temp_day)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> ferret_IAV_data, <span class="fu">aes</span>(<span class="at">x =</span> temp_day, <span class="at">y =</span> temp, <span class="at">col =</span> lethal), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>( <span class="at">x =</span> <span class="st">"day of maximum temperature"</span>, <span class="at">y =</span> <span class="st">"temperature"</span>, <span class="at">title =</span> <span class="st">"max temperature by day"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>plot10</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/temp-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="4" type="1">
<li>does day of max weight loss correlate with day of max temp?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>plot11 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> ferret_IAV_data, <span class="fu">aes</span>(<span class="at">x =</span> wt_loss_day, <span class="at">y =</span> temp_day, <span class="at">col =</span> lethal))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co">#lol no</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>plot11</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/wt-loss-temp-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>5)creating a dataframe of viral titres for each ferret! this is a skeleton code - there are wayyy to many samples here to be meaningful. Either we randomly sample to get a sense of the overall behavior, or we filter based on some other criteria. The choice is yours!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>time_series_titres <span class="ot">=</span> <span class="fu">as.vector</span>(<span class="fu">t</span>(<span class="fu">data.matrix</span>(ferret_IAV_data[,<span class="fu">grep</span>(<span class="st">"_inoc"</span>, <span class="fu">colnames</span>(ferret_IAV_data))]))) <span class="co">#transform a matrix of only titres variables into a matrix, transpose so that each row is a day and each column is a sample, and collapse into a vector </span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># the first 9 elements of vector time_series_titres contains the titres from days 1-9 for ferret 1, the next 9 for ferret 2, and so on. now, we want to create a dataframe with the sample ID of each ferret repeated 9s in one column, and the sequence of days 1:9 repeated 9 times in the other</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>time_series_titres <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">titre =</span> time_series_titres, </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Ferret =</span> <span class="fu">rep</span>(ferret_IAV_data<span class="sc">$</span>Ferret, <span class="at">each =</span> <span class="dv">9</span>), </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">DayPost =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">times =</span> <span class="fu">length</span>(ferret_IAV_data<span class="sc">$</span>Ferret)))</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> time_series_titres, <span class="fu">aes</span>(<span class="at">x =</span> DayPost, <span class="at">y =</span> titre, <span class="at">col =</span> Ferret), <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="co">#see? nothing to learn here, yet...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1960 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/virus-titres-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="this-section-is-contributed-by-taylor-glass." class="level2">
<h2 class="anchored" data-anchor-id="this-section-is-contributed-by-taylor-glass.">This section is contributed by Taylor Glass.</h2>
<p>I am going to make a synthetic data set to mirror this descriptive analysis by selecting 12 variables used to create the descriptive plots. I need an ID for the inoculated <code>Ferret</code>, an ID for the <code>Virus</code> used to inoculate it, whether the infection was <code>lethal</code>, if the infection was lethal, when the ferret died (<code>lethal_day</code>), whether the virus is a highly virulant avian <code>HPAI</code>, if the virus is highly virulent <code>HPAI</code>, whether it has a multi-basic amino acid cleavage site at HA, or an <code>HPAI_MBAA</code>, the identity of the virus’s <code>HA</code> and <code>NA</code> subtypes, the maximum percentage <code>wt_loss</code> of the ferret and which day this maximum was measured (<code>wt_loss_day</code>), and the maximum temperature <code>temp</code> of the ferret and which day this maximum was measured (<code>temp_day</code>). I will not generate a time series column because the code included in the descriptive analysis is only a skeleton, so I would have nothing to compare it to.</p>
<p>To get started, I asked ChatGPT 3.5 to create R code for a synthetic data set with these 12 variables by copying the previous paragraph into the AI tool and specifically asking for R code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="do">## load packages</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="do">## set seed for reproducibility</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="do">## original R code provided by ChatGPT</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="co"># set number of observations</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="co"># generate synthetic data</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">Ferret_ID =</span> <span class="dv">1</span><span class="sc">:</span>n,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Virus_ID =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">lethal =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">lethal_day =</span> <span class="fu">ifelse</span>(lethal <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="cn">NA</span>),</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">HPAI =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">HPAI_MBAA =</span> <span class="fu">ifelse</span>(HPAI <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="cn">NA</span>),</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">HA_subtype =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"H1"</span>, <span class="st">"H3"</span>, <span class="st">"H5"</span>, <span class="st">"H7"</span>, <span class="st">"H9"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">NA_subtype =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"N1"</span>, <span class="st">"N2"</span>, <span class="st">"N5"</span>, <span class="st">"N7"</span>, <span class="st">"N9"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">wt_loss =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">20</span>, <span class="at">sd =</span> <span class="dv">5</span>),</span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">wt_loss_day =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">temp =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">38</span>, <span class="at">sd =</span> <span class="fl">0.5</span>),</span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">temp_day =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a><span class="co"># print the first few rows of the synthetic dataset</span></span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  Ferret_ID Virus_ID lethal lethal_day HPAI  HPAI_MBAA HA_subtype NA_subtype
      &lt;int&gt;    &lt;int&gt; &lt;chr&gt;       &lt;int&gt; &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     
1         1        3 No             NA No    &lt;NA&gt;      H9         N9        
2         2        3 No             NA No    &lt;NA&gt;      H3         N7        
3         3       10 Yes             7 No    &lt;NA&gt;      H1         N7        
4         4        2 No             NA No    &lt;NA&gt;      H7         N7        
5         5        6 Yes             1 Yes   No        H3         N9        
6         6        5 Yes             9 No    &lt;NA&gt;      H3         N7        
# ℹ 4 more variables: wt_loss &lt;dbl&gt;, wt_loss_day &lt;int&gt;, temp &lt;dbl&gt;,
#   temp_day &lt;int&gt;</code></pre>
</div>
</div>
<p>The head of the new synthetic data set indicates that the ifelse statements were successful because there are NA values in the ‘lethal_day’ and ‘HPAI_MBAA’ variables. This makes sense because not every ferret died and not every HPAI virus had a multi-basic amino acid cleavage site at HA.</p>
<p>This data set is sufficient for modeling the original data set, but I made a few modifications to make it more similar to the real data. I want to include the same number of observations as the original data set, which is an easy change. The original synthetic data included 10 different virus IDs, but there are 83 different viral strands included in the real data. The real HA variable is a factor with 6 levels, and the real NA variable is a factor with 7 levels. I added 1 option to the HA_subtype variable and 2 options to the NA_subtype variable. I updated the ‘wt_loss’ and ‘temp’ variables with the true means and standard deviations of the real data. The real study was conducted over 14 days, so I made that change as well for the ‘wt_loss_day’ and ‘temp_day’ variables.</p>
<p>I returned to this code after generating the first few plots and added probabilities to the ‘lethal’ and ‘HPAI’ variables. I was originally getting an even distribution for both of these variables in the synthetic data, which does not accurately portray the real data. Adding these probabilities increased the accuracy of the synthetic data compared to the real data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># explore real data to make synthetic data more accurate </span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ferret_IAV_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 438  23</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ferret_IAV_data<span class="sc">$</span>Virus) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                      A/Albany/6/1958                      A/Alberta/1/2014 
                                    6                                     3 
     A/AmWigeon/SC/22-000345-001/2021               A/Anhui-Lujiang/39/2018 
                                    6                                     9 
               A/Bangladesh/5487/2011 A/BarnSwallow/Hong Kong/D10-1161/2010 
                                    3                                     6 
             A/Cambodia/X0123311/2013              A/Cambodia/X0810301/2013 
                                    3                                     3 
                    A/Canada/504/2004                A/canine/IL/12191/2015 
                                    6                                     3 
           A/chicken/Indonesia/7/2003               A/chicken/Korea/ES/2003 
                                    3                                     3 
           A/chicken/Korea/Gimje/2008               A/chicken/Korea/IS/2006 
                                    3                                     3 
           A/chicken/PA/298101-4/2004      A/chicken/Texas/18-007912-2/2018 
                                    6                                     3 
       A/chicken/Vietnam/NCVD/31/2004                 A/ck/CT/260413-2/2003 
                                    3                                     6 
             A/ck/TN/17-007147-2/2017              A/ck/TN/17-007431-3/2017 
                                    3                                     3 
               A/duck/Alberta/35/1976         A/duck/Bangladesh/19D770/2017 
                                    9                                     3 
        A/duck/New York/15024-21/1996         A/duck/Vietnam/NCVD-0004/2013 
                                    9                                     3 
        A/duck/Vietnam/NCVD-1206/2012         A/duck/Vietnam/NCVD-1232/2012 
                                    6                                     3 
        A/duck/Vietnam/NCVD-2848/2013          A/duck/Vietnam/NCVD-672/2011 
                                    3                                     3 
             A/Egypt/2321-NAMRU3/2007              A/Egypt/4935-NAMRU3/2009 
                                    3                                     3 
                  A/Egypt/N03072/2010                  A/El Salvador/2/1957 
                                    3                                     6 
                    A/England/10/1967         A/goose/Nebraska/17096-1/2011 
                                    9                                     3 
             A/goose/Vietnam/113/2001              A/Guangdong/17SF003/2016 
                                    3                                     6 
          A/gyrfalcon/WA/41088-6/2014                 A/Hong Kong/1073/1999 
                                    3                                     6 
                 A/Hong Kong/213/2003                  A/Hong Kong/308/2014 
                                    6                                     6 
                A/Hong Kong/4553/2016                  A/Hong Kong/486/1997 
                                    6                                     8 
                   A/Indonesia/5/2005               A/Indonesia/CDC625/2006 
                                   20                                     3 
                       A/Italy/3/2013            A/Mallard/Alberta/119/1998 
                                    3                                     3 
          A/mallard/Maryland/235/2001          A/mallard/New York/6750/1978 
                                    6                                     9 
                   A/Mexico/4482/2009                    A/Mexico/7218/2012 
                                   20                                     3 
                  A/Minnesota/11/2010                   A/Nanchang/933/1995 
                                    3                                     3 
               A/Netherlands/219/2003                A/Netherlands/230/2003 
                                    9                                    12 
              A/New Caledonia/20/1999                   A/New York/107/2003 
                                    7                                    19 
                  A/New York/108/2016                    A/New York/55/2004 
                                    6                                     7 
     A/Northern pintail/WA/40964/2014                    A/Panama/2007/1999 
                                    3                                     3 
                 A/Sichuan/26221/2014             A/Solomon Islands/03/2006 
                                    3                                     3 
                A/South Dakota/6/2007               A/swine/MO/2124514/2006 
                                   16                                     6 
              A/swine/MO/4296424/2006                       A/Taiwan/1/2017 
                                    3                                     6 
                   A/Thailand/16/2004               A/Thailand/Kan/353/2004 
                                    3                                     3 
                 A/Thailand/SP83/2004  A/turkey/California/18-031151-4/2018 
                                    3                                     3 
           A/Turkey/Indiana/1403/2016         A/Turkey/Indiana/1573-02/2016 
                                    3                                     3 
            A/turkey/Kansas/4880/1980         A/turkey/Minnesota/10915/2015 
                                    3                                     3 
                A/turkey/SD/7034/1986                 A/Turkey/VA/4529/2002 
                                    3                                     9 
                    A/Victoria/3/1975                   A/Vietnam/1203/2004 
                                    6                                    11 
                  A/Vietnam/1204/2004                A/Vietnam/HN30408/2005 
                                    3                                     3 
                A/Vietnam/VP12-3/2012               A/Vietnam/VP13-28H/2013 
                                    3                                     3 
                  A/Yunnan/14563/2015 
                                    3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ferret_IAV_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   438 obs. of  23 variables:
 $ Ferret     : chr  "F1" "F2" "F3" "F4" ...
 $ Virus      : chr  "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" "A/Turkey/VA/4529/2002" ...
 $ units      : Factor w/ 2 levels "EID","PFU": 1 1 1 1 1 1 1 1 1 1 ...
 $ lethal     : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ lethal_day : int  NA NA NA NA NA NA NA NA NA NA ...
 $ HPAI       : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ HPAI_MBAA  : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ HA         : Factor w/ 6 levels "H1","H2","H3",..: 5 5 5 5 5 5 5 5 5 5 ...
 $ NA.        : Factor w/ 7 levels "N1","N2","N3",..: 2 2 2 2 2 2 2 2 2 5 ...
 $ wt_loss    : num  6.7 11.8 15.4 5.9 7.9 6.1 3.5 22.5 15 14.9 ...
 $ wt_loss_day: int  7 4 6 11 5 9 11 7 7 8 ...
 $ temp       : num  0.5 0.9 2 1 1 0.5 0.5 1.1 1.1 1 ...
 $ temp_day   : int  4 7 8 9 3 3 7 7 7 1 ...
 $ d1_inoc    : num  6.5 5.5 6.25 6.75 6.25 7.25 5.75 5.75 4.75 6.5 ...
 $ d2_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d3_inoc    : num  4.5 6.5 5.5 6.75 6.5 6.75 5.75 5.5 3.75 5.25 ...
 $ d4_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d5_inoc    : num  4.75 4.75 5.75 5.75 4.75 4.5 5.75 5.5 5.25 6.5 ...
 $ d6_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d7_inoc    : num  1.75 1.5 1.5 3.25 1.5 1.5 1.5 2.25 1.5 3.25 ...
 $ d8_inoc    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ d9_inoc    : num  1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 ...
 $ subtype    : Factor w/ 15 levels "H1N1","H2N2",..: 10 10 10 10 10 10 10 10 10 12 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ferret_IAV_data<span class="sc">$</span>wt_loss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   4.200   9.000   9.803  15.000  27.200       1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(ferret_IAV_data<span class="sc">$</span>wt_loss, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.957058</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ferret_IAV_data<span class="sc">$</span>temp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   1.100   1.700   1.694   2.300   4.000       2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(ferret_IAV_data<span class="sc">$</span>temp, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7716429</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(ferret_IAV_data<span class="sc">$</span>wt_loss_day)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0 14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set seed for reproducibility </span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">125</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># set number of observations</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">438</span> <span class="co">#match the number of observations from the original data set</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="co"># generate synthetic data</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Ferret_ID =</span> <span class="dv">1</span><span class="sc">:</span>n,</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Virus_ID =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">83</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="co">#increase number of viral strand options</span></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">lethal =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.8</span>)),</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">lethal_day =</span> <span class="fu">ifelse</span>(lethal <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="cn">NA</span>),</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">HPAI =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.9</span>, <span class="fl">0.1</span>)),</span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">HPAI_MBAA =</span> <span class="fu">ifelse</span>(HPAI <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="cn">NA</span>),</span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">HA_subtype =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"H1"</span>, <span class="st">"H3"</span>, <span class="st">"H5"</span>, <span class="st">"H7"</span>, <span class="st">"H9"</span>, <span class="st">"H11"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="co">#add another level</span></span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">NA_subtype =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"N1"</span>, <span class="st">"N2"</span>, <span class="st">"N5"</span>, <span class="st">"N7"</span>, <span class="st">"N9"</span>, <span class="st">"N10"</span>, <span class="st">"N12"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="co">#add 2 more level</span></span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">wt_loss =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="fl">9.803</span>, <span class="at">sd =</span> <span class="fl">6.957</span>), <span class="co">#true mean and sd from the data</span></span>
<span id="cb59-18"><a href="#cb59-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">wt_loss_day =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">14</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="co">#real study time period</span></span>
<span id="cb59-19"><a href="#cb59-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">temp =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="fl">1.694</span>, <span class="at">sd =</span> <span class="fl">0.772</span>), <span class="co">#true mean and sd from the data</span></span>
<span id="cb59-20"><a href="#cb59-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">temp_day =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">14</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="co">#real study time period</span></span>
<span id="cb59-21"><a href="#cb59-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb59-22"><a href="#cb59-22" aria-hidden="true" tabindex="-1"></a><span class="co"># print the first few rows of the synthetic data set</span></span>
<span id="cb59-23"><a href="#cb59-23" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  Ferret_ID Virus_ID lethal lethal_day HPAI  HPAI_MBAA HA_subtype NA_subtype
      &lt;int&gt;    &lt;int&gt; &lt;chr&gt;       &lt;int&gt; &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     
1         1        3 No             NA No    &lt;NA&gt;      H9         N9        
2         2        3 No             NA No    &lt;NA&gt;      H3         N7        
3         3       10 Yes             7 No    &lt;NA&gt;      H1         N7        
4         4        2 No             NA No    &lt;NA&gt;      H7         N7        
5         5        6 Yes             1 Yes   No        H3         N9        
6         6        5 Yes             9 No    &lt;NA&gt;      H3         N7        
# ℹ 4 more variables: wt_loss &lt;dbl&gt;, wt_loss_day &lt;int&gt;, temp &lt;dbl&gt;,
#   temp_day &lt;int&gt;</code></pre>
</div>
</div>
<p>Now that I have an accurate synthetic data set, I can create some of the plots originally used to explore the data. I will explore lethality first with a simple histogram. The synthetic data produced approximately 79 deaths and 360 survivals, and the real data only had 90 deaths compared to 348 survivals. After creating a boxplot to display how many days each ferret that died survived, the mean survival time was about 6 days for 79 lethal observations, compared to the real findings of a mean survival time around 7 days for 90 lethal observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create visualization of ferret death</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>hist1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data2, <span class="fu">aes</span>(<span class="at">x=</span>lethal)) <span class="sc">+</span> </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>(<span class="at">x=</span> <span class="st">"Ferret Death"</span>,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y=</span> <span class="st">"Frequency"</span>, </span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">"Synthetic Data Ferret Death"</span>)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>hist1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="do">## compare with the same plot of the real data</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>plot1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create visualization of mean survival time among ferrets that died </span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>boxplot1 <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">filter</span>(lethal <span class="sc">==</span> <span class="st">"Yes"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> lethal_day)) <span class="sc">+</span> </span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">annotate</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="fl">7.5</span>, <span class="at">label =</span> <span class="fu">paste</span>(<span class="fu">sum</span>(data2<span class="sc">$</span>lethal<span class="sc">==</span><span class="st">"Yes"</span>), <span class="st">"lethal                         observations"</span>)) <span class="sc">+</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Ferret Death"</span>,</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> <span class="st">"Days Survived"</span>,</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">"Synthetic Data Days Survived"</span>)</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>boxplot1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="do">## compare with the same plot of the real data</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>plot2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-3-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I explored how many of the virulent strains are highly pathogenic in the synthetic data set next. The synthetic data showed 72 highly pathogenic HPAI strands among ferrets that died compared to 7 dead ferrets without highly pathogenic HPAI strands. This is similar to the 89 observations of highly pathogenic viruses in dead ferrets compared to 1 non-highly pathogenic virus in dead ferrets that was recorded in the real data set. The synthetic data differs from the real data when exploring how many ferrets infected with highly pathogenic HPAI strands. Only 72 ferrets infected with HPAI died and 323 survived compared to 89 ferrets infected with HPAI dying and 118 ferrets surviving in the real data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create visualization of dead ferrets with HPAI strands</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>hist2 <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(<span class="st">"HPAI"</span>, <span class="st">"lethal"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">filter</span>(lethal <span class="sc">==</span> <span class="st">"Yes"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> HPAI, <span class="at">y =</span> (..count..)<span class="sc">/</span><span class="fu">sum</span>(..count..))) <span class="sc">+</span> </span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">stat_count</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> HPAI, <span class="at">label =</span> <span class="fu">paste</span>(..count.., <span class="st">"observations"</span>), <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="fu">sum</span>(data2<span class="sc">$</span>lethal<span class="sc">==</span><span class="st">"Yes"</span>)))) <span class="sc">+</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Highly Pathogenic HPAI"</span>, </span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> <span class="st">"Frequency"</span>, </span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">"Synthetic Data Dead Ferrets with Highly Pathogenic HPAI"</span>)</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>hist2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="do">## compare with the same plot of the real data</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>plot3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create visualization of HPAI strands in dead ferrets</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>hist3 <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(<span class="st">"HPAI"</span>, <span class="st">"lethal"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">filter</span>(HPAI <span class="sc">==</span> <span class="st">"Yes"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> lethal, <span class="at">y =</span> (..count..)<span class="sc">/</span><span class="fu">sum</span>(..count..))) <span class="sc">+</span> </span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">stat_count</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> lethal, <span class="at">label =</span> <span class="fu">paste</span>(..count.., <span class="st">"observations"</span>), <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">sum</span>(data2<span class="sc">$</span>HPAI<span class="sc">==</span><span class="st">"Yes"</span>)))) <span class="sc">+</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Dead Ferrets"</span>, </span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> <span class="st">"Frequency"</span>, </span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">"Synthetic Data Percentage Ferrets Infected with Highly Pathogenic HPAI that Died"</span>)</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>hist3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="do">## compare with the same plot of the real data</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>plot4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I also wanted to explore a couple of the descriptive questions that were answered with the real data set. First, what is the distribution of NA and HA subtypes? How do those subtypes appear in combination? I had to add a new variable to the synthetic data set to mimic what was done to the real data set. These plots differ a lot between the synthetic data and the real data because the synthetic data has many more combinations of HA and NA subtypes with a much higher proportion of each subtype being classified as HPAI. I think the synthetic data created more subtypes that do not actually exist in the real world considering that there are only 15 subtype combination shown in the real data, which would explain why the distributions look different.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add new subtype variable</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span> </span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">mutate</span>(<span class="at">subtype =</span> <span class="fu">as.factor</span>(<span class="fu">paste0</span>(HA_subtype,NA_subtype)))  </span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create visualization of viral subtype combinations and HPAI classification</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>boxplot2 <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> subtype, <span class="at">y =</span> ..count..<span class="sc">/</span><span class="fu">sum</span>(..count..), <span class="at">fill =</span> HPAI)) <span class="sc">+</span>  <span class="co">#kept the same colors</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">stat_count</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">2.5</span>, <span class="fu">aes</span>(<span class="at">x =</span> subtype, <span class="at">label =</span> ..count.., <span class="at">y =</span> ..count..<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">length</span>(data2<span class="sc">$</span>subtype)))) <span class="sc">+</span></span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Subtype"</span>, </span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> <span class="st">"Proportion"</span>, </span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">"Synthetic Data Proportion of Inoculated Influenza A Subtypes"</span> )</span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>boxplot2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="do">## compare with the same plot of the real data</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>plot8</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I explored how much weight loss each ferret exhibited and stratified that based on lethal status in the synthetic data as was done for the real data. The synthetic data plot shows a more consistence percentage of weight loss around 10% across the 14 day time period while the real data shows an increase in weight loss percentage over the first 4 days before the average hovers around 10% for the remainder of the time. Additionally, the real data boxplots show that ferrets that died had higher weight loss based on the blue dots, but that trend is not seen in the synthetic data. I think the reason for this discrepancy is that there is a correlation because weight loss and lethality that was not accounted for in the synthetic data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create visualization of the weight loss in ferrets over 14 days</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>boxplot3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_boxplot</span>(<span class="at">data =</span> data2, <span class="fu">aes</span>(<span class="at">x =</span> wt_loss_day, <span class="at">y =</span> wt_loss, <span class="at">group =</span> wt_loss_day)) <span class="sc">+</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_point</span>(<span class="at">data =</span> data2, <span class="fu">aes</span>(<span class="at">x =</span> wt_loss_day, <span class="at">y =</span> wt_loss, <span class="at">col =</span> lethal), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>( <span class="at">x =</span> <span class="st">"Day of Maximum Weight Loss"</span>, </span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">y =</span> <span class="st">"Percentage Weight Loss"</span>, </span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">title =</span> <span class="st">"Synthetic Data Max Percentage Weight Loss By Day"</span>)</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>boxplot3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="do">## compare with the same plot of the real data</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>plot9</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Lastly, I would expect there to be no correlation between weight loss day and day of maximum temperature in the synthetic data because there is no correlation between these two variables in the real data. These expectation were met based on the ‘scatter1’ plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create visualization of correlation between weight loss day and maximum temperature day</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>scatter1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_point</span>(<span class="at">data =</span> data2, <span class="fu">aes</span>(<span class="at">x =</span> wt_loss_day, <span class="at">y =</span> temp_day, <span class="at">col =</span> lethal))</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>scatter1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="do">## compare with the same plot of the real data</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>plot11 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> ferret_IAV_data, <span class="fu">aes</span>(<span class="at">x =</span> wt_loss_day, <span class="at">y =</span> temp_day, <span class="at">col =</span> lethal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Overall, the synthetic data did a sufficient job of modeling the real data in terms of how many ferrets died and which ones had the highly pathogenic HPAI strands because the probability of each of these variables was accounted for. The least successful synthetic data plot came from subtypes of viral strands based on the different number of combinations between the synthetic and real data. I think this could be improved if there was a way to account for the 15 subtype combinations that actually exist in the real data.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>