<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Cora Hirst Data Analysis Portfolio - R Coding Exercise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Cora Hirst Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html" rel="" target="">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html" rel="" target="">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html" rel="" target="">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html" rel="" target="">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/code/data-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdc-exercise/code/cdcdata-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Analysis Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/CoraHirst/corahirst-MADA-portfolio" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R Coding Exercise</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="purpose" class="level1">
<h1>Purpose</h1>
<p>The following is an R coding excerise on loading, viewing, processing, and visualizing data in R. We complete all analysis on the <code>gapminder</code> dataset.</p>
<p>All code chunks are echoed for ease of viewing.</p>
<p>The following chunk loads all libraries which will be used during this exercise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## install packages and load required libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("dslabs") #lines to install required packages are commented</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs) <span class="co">#load dslabs library</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("tidyverse") #install and load tidyverse</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("here")</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/chirst/Desktop/Git/corahirst-MADA-portfolio</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("gtsummary")</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>#StandWithUkraine</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("flextable")</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'flextable'

The following objects are masked from 'package:gtsummary':

    as_flextable, continuous_summary

The following object is masked from 'package:purrr':

    compose</code></pre>
</div>
</div>
</section>
<section id="loading-and-checking-the-data" class="level1">
<h1>Loading and checking the data</h1>
<p>Below, we familiarize ourselves with the most recent dataset from the package <code>gapminder</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pull information on the gapminder package</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(gapminder) <span class="co">#open help file for gapminder dataset</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># structure of the gapminder dataset?</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(gapminder) <span class="co"># what is the class of the gapminder dataset? how many variables? class of each variable?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10545 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...
 $ infant_mortality: num  115.4 148.2 208 NA 59.9 ...
 $ life_expectancy : num  62.9 47.5 36 63 65.4 ...
 $ fertility       : num  6.19 7.65 7.32 4.43 3.11 4.55 4.82 3.45 2.7 5.57 ...
 $ population      : num  1636054 11124892 5270844 54681 20619075 ...
 $ gdp             : num  NA 1.38e+10 NA NA 1.08e+11 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 4 1 1 2 2 3 2 5 4 3 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 19 11 10 2 15 21 2 1 22 21 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summarize the gapminder data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gapminder) <span class="co">#gives summary statistics for each numeric variable and count information for each categorical variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                country           year      infant_mortality life_expectancy
 Albania            :   57   Min.   :1960   Min.   :  1.50   Min.   :13.20  
 Algeria            :   57   1st Qu.:1974   1st Qu.: 16.00   1st Qu.:57.50  
 Angola             :   57   Median :1988   Median : 41.50   Median :67.54  
 Antigua and Barbuda:   57   Mean   :1988   Mean   : 55.31   Mean   :64.81  
 Argentina          :   57   3rd Qu.:2002   3rd Qu.: 85.10   3rd Qu.:73.00  
 Armenia            :   57   Max.   :2016   Max.   :276.90   Max.   :83.90  
 (Other)            :10203                  NA's   :1453                    
   fertility       population             gdp               continent   
 Min.   :0.840   Min.   :3.124e+04   Min.   :4.040e+07   Africa  :2907  
 1st Qu.:2.200   1st Qu.:1.333e+06   1st Qu.:1.846e+09   Americas:2052  
 Median :3.750   Median :5.009e+06   Median :7.794e+09   Asia    :2679  
 Mean   :4.084   Mean   :2.701e+07   Mean   :1.480e+11   Europe  :2223  
 3rd Qu.:6.000   3rd Qu.:1.523e+07   3rd Qu.:5.540e+10   Oceania : 684  
 Max.   :9.220   Max.   :1.376e+09   Max.   :1.174e+13                  
 NA's   :187     NA's   :185         NA's   :2972                       
             region    
 Western Asia   :1026  
 Eastern Africa : 912  
 Western Africa : 912  
 Caribbean      : 741  
 South America  : 684  
 Southern Europe: 684  
 (Other)        :5586  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># although the str() function gives the dataset class, we can check with the function class()</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(gapminder) <span class="co">#gives the class of the r object gapminder</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p>The <code>gapminder</code> dataset is an object of class “data.frame”. Each row of the dataframe contains health and income outcomes for some year for some country. The dataframe contains 9 columns, for <code>country</code> name, <code>region</code>, and <code>continent</code>; the <code>year</code> of the observation; and 5 different demographic, health, and income outcomes for each observation. These outcomes consist of <code>infant_mortality</code>, <code>life_expectancy</code>, <code>fertility</code>, <code>population</code>, and <code>gdp</code>.</p>
<p>There are 10545 observations in total, gathered from 184 countries between the years of 1960 and 2016.</p>
</section>
<section id="processing-the-data" class="level1">
<h1>Processing the data</h1>
<p>Here, we are going to select and process data on african countries from the <code>gapminder</code> dataset.m</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset rows from dataset containing factor level 'Africa' from column "continent"</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>africadata <span class="ot">=</span> gapminder <span class="sc">%&gt;%</span> <span class="fu">filter</span>(continent <span class="sc">==</span> <span class="st">"Africa"</span>) <span class="co">#dplyr's filter() function accomplishes this</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create life expectancy subsets of africadata containing 1) infant mortality and life expectancy and 2) population and life expectancy </span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>africa.IMvsLE <span class="ot">=</span> africadata <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="st">"infant_mortality"</span>, <span class="st">"life_expectancy"</span>) <span class="co">#dplyrs select() function subsets columns</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>africa.PvsLE <span class="ot">=</span> africadata <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="st">"population"</span>, <span class="st">"life_expectancy"</span>) </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># structure of the life expectancy subsets</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africa.IMvsLE) <span class="co">#2907 observations, 2 columns (variables)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  2 variables:
 $ infant_mortality: num  148 208 187 116 161 ...
 $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africa.PvsLE) <span class="co">#2907 observations, 2 columns (variables)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  2 variables:
 $ population     : num  11124892 5270844 2431620 524029 4829291 ...
 $ life_expectancy: num  47.5 36 38.3 50.3 35.2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary of variables in life expectancy subsets</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africa.IMvsLE) <span class="co">#summary stats of both columns containing numerical values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> infant_mortality life_expectancy
 Min.   : 11.40   Min.   :13.20  
 1st Qu.: 62.20   1st Qu.:48.23  
 Median : 93.40   Median :53.98  
 Mean   : 95.12   Mean   :54.38  
 3rd Qu.:124.70   3rd Qu.:60.10  
 Max.   :237.40   Max.   :77.60  
 NA's   :226                     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africa.PvsLE) <span class="co">#summary stats of both columns contain numerical values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   population        life_expectancy
 Min.   :    41538   Min.   :13.20  
 1st Qu.:  1605232   1st Qu.:48.23  
 Median :  5570982   Median :53.98  
 Mean   : 12235961   Mean   :54.38  
 3rd Qu.: 13888152   3rd Qu.:60.10  
 Max.   :182201962   Max.   :77.60  
 NA's   :51                         </code></pre>
</div>
</div>
<p>The code chunk above isolates the 2907 observations from african countries only within the <code>gapminder</code> dataset and stores this subset in the “data.frame” object, <code>africandata</code>. Two subsets of the <code>africandata</code> data frame are generated. The first, <code>africa.IMvsLE</code>, contains two columns showing the values of variables <code>infant_mortality</code> and <code>life_expectancy</code> for each observation. The second, <code>africa.PvsLE</code>, contains two columns showing the values of variables <code>population</code> and <code>life_expectancy</code> for each observation.</p>
</section>
<section id="plotting" class="level1">
<h1>Plotting</h1>
<p>The following code chunk generates two plots, visualizing the association of either <code>infant_mortality</code> or <code>population</code> with <code>life_expectancy</code> across Africa between 1960-2016.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#life_expectancy vs infant_mortality </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> africa.IMvsLE, <span class="fu">aes</span>(<span class="at">x =</span> infant_mortality, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"infant mortality"</span>, <span class="at">y =</span> <span class="st">"life expectancy"</span>, <span class="at">title =</span> <span class="st">"correlation between life expectancy and infant mortality in Africa, 1960 - 2016"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> africa.PvsLE, <span class="fu">aes</span>(<span class="at">x =</span> population, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span> </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">"log"</span>) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"population"</span>, <span class="at">y =</span> <span class="st">"life expectancy"</span>, <span class="at">title =</span> <span class="st">"correlation between life expectancy and population size, 1960-2016"</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"figures"</span>,<span class="st">"life_exp_inf_mort_all.png"</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot1) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 226 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"figures"</span>,<span class="st">"life_exp_pop_all.png"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot2) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 51 rows containing missing values (`geom_point()`).</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-inf-mort-all" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results/figures/life_exp_inf_mort_all.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;1: life expectancy by infant mortality, Africa, 1960-2016.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pop-all" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results/figures/life_exp_pop_all.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;2: life expectancy by population size, Africa, 1960-2016.</figcaption>
</figure>
</div>
</div>
</div>
<p>Obviously, there appear to be clusters of data associated with the variables <code>infant_mortality</code> and <code>population</code>. These clusters may be the result of fixed effects from another associated variable, such as <code>year</code>.</p>
<p>The code chunk below regenerates these figures, with points colored by the year during which the observations were reported. Notice that I am now using the <code>africadata</code> subset to generate these figures, as this dataset also contains the <code>year</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">## life_expectancy vs infant_mortality stratified by year</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> africadata, <span class="fu">aes</span>(<span class="at">x =</span> infant_mortality, <span class="at">y =</span> life_expectancy, <span class="at">col =</span> <span class="fu">as.factor</span>(year))) <span class="sc">+</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"infant mortality"</span>, <span class="at">y =</span> <span class="st">"life expectancy"</span>, <span class="at">title =</span> <span class="st">"correlation between life expectancy and infant mortality in Africa, 1960 - 2016"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> africadata, <span class="fu">aes</span>(<span class="at">x =</span> population, <span class="at">y =</span> life_expectancy, <span class="at">col =</span> <span class="fu">as.factor</span>(year))) <span class="sc">+</span> </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">"log"</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"population"</span>, <span class="at">y =</span> <span class="st">"life expectancy"</span>, <span class="at">title =</span> <span class="st">"correlation between life expectancy and population size, 1960-2016"</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"figures"</span>,<span class="st">"life_exp_inf_mort_byyears.png"</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot3) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 226 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"figures"</span>,<span class="st">"life_exp_pop_byyears.png"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot4) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 51 rows containing missing values (`geom_point()`).</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-inf-mort-byyears" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results/figures/life_exp_inf_mort_byyears.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;3: life expectancy by infant mortality, Africa, by year.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pop-byyears" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results/figures/life_exp_pop_byyears.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;4: life expectancy by population size, Africa, by year.</figcaption>
</figure>
</div>
</div>
</div>
<p>Here, we see that “lines” in our data demonstrate how population size and infant mortality each correlate with year. However, this is visually difficult to disentangle. What we can see, particularly from our second plot, is that life expectancy appears somewhat constant across a range of population sizes within the same year.</p>
<p>Let’s recreate these plots, but only choose observations from a single year.</p>
<section id="more-processing" class="level2">
<h2 class="anchored" data-anchor-id="more-processing">More processing</h2>
<p>The <code>infant_mortality</code> variable within <code>africandata</code> contains many NAs. The code below determines which years contain missing (NA) data for infant mortality.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## determine which years contain missing infant mortality data</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>missing_IM_years <span class="ot">=</span> <span class="fu">levels</span>(<span class="fu">factor</span>(africadata[<span class="fu">is.na</span>(africadata<span class="sc">$</span>infant_mortality), <span class="st">"year"</span>])) <span class="co"># which levels of factor "year" contain missing data for vairable "infant mortality"?</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Infant mortality data is missing from the years"</span>, <span class="fu">paste</span>(missing_IM_years, <span class="at">collapse =</span> <span class="st">" "</span>))) <span class="co">#print these years</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Infant mortality data is missing from the years 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 2016"</code></pre>
</div>
</div>
<p>Infant mortality data is missing from observations between 1960-1981, and again from 2016. Between 1981 and 2016, then, every observation from each year contains infant mortality data. So, we will plot <code>life_expectancy</code> against <code>infant_mortality</code> from observations taken during a year within that time frame, say, the year 2000.</p>
</section>
<section id="more-plotting" class="level2">
<h2 class="anchored" data-anchor-id="more-plotting">More plotting</h2>
<p>The variable <code>population</code> is not missing data from the year 2000, so we can also plot <code>life expectancy</code> against <code>population</code> for observations taken in 2000, as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## extract observations from the year 2000 only and save in a new dataframe</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>africadata_2000 <span class="ot">=</span> africadata <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2000</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="do">## check </span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africadata_2000) <span class="co">#all variables from africadata included</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   51 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 2 3 18 22 26 27 29 31 32 33 ...
 $ year            : int  2000 2000 2000 2000 2000 2000 2000 2000 2000 2000 ...
 $ infant_mortality: num  33.9 128.3 89.3 52.4 96.2 ...
 $ life_expectancy : num  73.3 52.3 57.2 47.6 52.6 46.7 54.3 68.4 45.3 51.5 ...
 $ fertility       : num  2.51 6.84 5.98 3.41 6.59 7.06 5.62 3.7 5.45 7.35 ...
 $ population      : num  31183658 15058638 6949366 1736579 11607944 ...
 $ gdp             : num  5.48e+10 9.13e+09 2.25e+09 5.63e+09 2.61e+09 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 11 10 20 17 20 5 10 20 10 10 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africadata_2000) <span class="co">#and each variable is of the same class as corresponding africadata variables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         country        year      infant_mortality life_expectancy
 Algeria     : 1   Min.   :2000   Min.   : 12.30   Min.   :37.60  
 Angola      : 1   1st Qu.:2000   1st Qu.: 60.80   1st Qu.:51.75  
 Benin       : 1   Median :2000   Median : 80.30   Median :54.30  
 Botswana    : 1   Mean   :2000   Mean   : 78.93   Mean   :56.36  
 Burkina Faso: 1   3rd Qu.:2000   3rd Qu.:103.30   3rd Qu.:60.00  
 Burundi     : 1   Max.   :2000   Max.   :143.30   Max.   :75.00  
 (Other)     :45                                                  
   fertility       population             gdp               continent 
 Min.   :1.990   Min.   :    81154   Min.   :2.019e+08   Africa  :51  
 1st Qu.:4.150   1st Qu.:  2304687   1st Qu.:1.274e+09   Americas: 0  
 Median :5.550   Median :  8799165   Median :3.238e+09   Asia    : 0  
 Mean   :5.156   Mean   : 15659800   Mean   :1.155e+10   Europe  : 0  
 3rd Qu.:5.960   3rd Qu.: 17391242   3rd Qu.:8.654e+09   Oceania : 0  
 Max.   :7.730   Max.   :122876723   Max.   :1.329e+11                
                                                                      
                       region  
 Eastern Africa           :16  
 Western Africa           :16  
 Middle Africa            : 8  
 Northern Africa          : 6  
 Southern Africa          : 5  
 Australia and New Zealand: 0  
 (Other)                  : 0  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="do">## plot</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="do">## life_expectancy vs infant_mortality in the year 2000</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>plot5 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> africadata_2000, <span class="fu">aes</span>(<span class="at">x =</span> infant_mortality, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span> </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> africadata_2000, <span class="fu">aes</span>(<span class="at">x =</span> infant_mortality, <span class="at">y =</span> life_expectancy), <span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"infant mortality"</span>, <span class="at">y =</span> <span class="st">"life expectancy"</span>, <span class="at">title =</span> <span class="st">"correlation between life expectancy and infant mortality in Africa, year 2000"</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>plot6 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> africadata_2000, <span class="fu">aes</span>(<span class="at">x =</span> population, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span> </span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">"log"</span>) <span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> africadata_2000, <span class="fu">aes</span>(<span class="at">x =</span> population, <span class="at">y =</span> life_expectancy), <span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"population"</span>, <span class="at">y =</span> <span class="st">"life expectancy"</span>, <span class="at">title =</span> <span class="st">"correlation between life expectancy and population size, year 2000"</span>)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"figures"</span>,<span class="st">"life_exp_inf_mort_2000.png"</span>)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot5) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"figures"</span>,<span class="st">"life_exp_pop_2000.png"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot6) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-inf-mort-2000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results/figures/life_exp_inf_mort_2000.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;5: life expectancy by infant mortality, Africa 2000.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pop-2000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results/figures/life_exp_pop_2000.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;6: life expectancy by population size, Africa 2000.</figcaption>
</figure>
</div>
</div>
</div>
<p>Are these correlations (linear regressions) significant?</p>
</section>
<section id="simple-model-fits" class="level2">
<h2 class="anchored" data-anchor-id="simple-model-fits">Simple model fits</h2>
<p>The following code chunk utilizes the <code>lm()</code> function in R to determine the best-fit, simple linear regression model with <code>life_expectancy</code> in the year 2000 as the outcome variable and either <code>infant_mortality</code> or <code>population</code> as the predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear regression, fixed effect, life expectancy ~ infant_mortality</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">data =</span> africadata_2000, life_expectancy <span class="sc">~</span> infant_mortality) <span class="co">#results saved in lm object `fit1`</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># linear regression, fixed effect, life expectancy ~ infant_mortality</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">data =</span> africadata_2000, life_expectancy <span class="sc">~</span> population) <span class="co">#results saved in lm object `fit2`</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># print summary of lm objects fit1 and fit2</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_expectancy ~ infant_mortality, data = africadata_2000)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.6651  -3.7087   0.9914   4.0408   8.6817 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      71.29331    2.42611  29.386  &lt; 2e-16 ***
infant_mortality -0.18916    0.02869  -6.594 2.83e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.221 on 49 degrees of freedom
Multiple R-squared:  0.4701,    Adjusted R-squared:  0.4593 
F-statistic: 43.48 on 1 and 49 DF,  p-value: 2.826e-08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_expectancy ~ population, data = africadata_2000)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.429  -4.602  -2.568   3.800  18.802 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 5.593e+01  1.468e+00  38.097   &lt;2e-16 ***
population  2.756e-08  5.459e-08   0.505    0.616    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.524 on 49 degrees of freedom
Multiple R-squared:  0.005176,  Adjusted R-squared:  -0.01513 
F-statistic: 0.2549 on 1 and 49 DF,  p-value: 0.6159</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">=</span> fit1 <span class="sc">%&gt;%</span> <span class="fu">tbl_regression</span>() <span class="co">#save summaries as tables using tbl_regression() function from flextable package</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>table2 <span class="ot">=</span> fit2 <span class="sc">%&gt;%</span> <span class="fu">tbl_regression</span>() <span class="co">#save summaries as tables using tbl_regression() function from flextable package</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># save summary tables</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"tables-files"</span>, <span class="st">"lm_life_exp_inf_mort.rds"</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table1, <span class="at">file =</span> summarytable_file)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>summarytable_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"tables-files"</span>, <span class="st">"lm_life_exp_pop.rds"</span>)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(table2, <span class="at">file =</span> summarytable_file)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co"># extract p-values from summaries to display on figures</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>p.infant_mortality <span class="ot">=</span> <span class="fu">unname</span>(<span class="fu">summary</span>(fit1)<span class="sc">$</span>coefficients[,<span class="st">"Pr(&gt;|t|)"</span>])[<span class="dv">2</span>]</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>p.population <span class="ot">=</span> <span class="fu">unname</span>(<span class="fu">summary</span>(fit2)<span class="sc">$</span>coefficients[,<span class="st">"Pr(&gt;|t|)"</span>])[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-lm_life_exp_inf_mort-2000" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1: Linear regression model of life expectancy by infant mortality.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Beta</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">infant_mortality</td>
<td style="text-align: left;">-0.19</td>
<td style="text-align: left;">-0.25, -0.13</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-lm_life_exp_pop-2000" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2: Linear regression model of life expectancy by population size.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Beta</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">population</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">0.00, 0.00</td>
<td style="text-align: left;">0.6</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="do">## replot with pvals </span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="do">## life_expectancy vs infant_mortality in the year 2000</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>plot7 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> africadata_2000, <span class="fu">aes</span>(<span class="at">x =</span> infant_mortality, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span> </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> africadata_2000, <span class="fu">aes</span>(<span class="at">x =</span> infant_mortality, <span class="at">y =</span> life_expectancy), <span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">125</span>, <span class="at">y =</span> <span class="dv">70</span>, <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"p-value ="</span>, <span class="fu">signif</span>(p.infant_mortality, <span class="at">digits =</span> <span class="dv">3</span>)), <span class="at">color =</span> <span class="st">"forestgreen"</span>) <span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"infant mortality"</span>, <span class="at">y =</span> <span class="st">"life expectancy"</span>, <span class="at">title =</span> <span class="st">"correlation between life expectancy and infant mortality in Africa, year 2000"</span>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>plot8 <span class="ot">=</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> africadata_2000, <span class="fu">aes</span>(<span class="at">x =</span> population, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span> </span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">"log"</span>) <span class="sc">+</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> africadata_2000, <span class="fu">aes</span>(<span class="at">x =</span> population, <span class="at">y =</span> life_expectancy), <span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom =</span> <span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">163000</span>, <span class="at">y =</span> <span class="dv">40</span>, <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"p-value ="</span>, <span class="fu">signif</span>(p.population, <span class="at">digits =</span> <span class="dv">3</span>)), <span class="at">color =</span> <span class="st">"maroon"</span>) <span class="sc">+</span></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"population"</span>, <span class="at">y =</span> <span class="st">"life expectancy"</span>, <span class="at">title =</span> <span class="st">"correlation between life expectancy and population size, year 2000"</span>)</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"figures"</span>,<span class="st">"life_exp_inf_mort_reg.png"</span>)</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot7) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">=</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>, <span class="st">"figures"</span>,<span class="st">"life_exp_pop_reg.png"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot=</span>plot8) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-reg-inf-mort-2000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results/figures/life_exp_inf_mort_reg.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;7: linear regression of life expectancy by infant mortality, Africa 2000.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-reg-pop-2000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results/figures/life_exp_pop_reg.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;8: linear regression of life expectancy by population size, Africa 2000.</figcaption>
</figure>
</div>
</div>
</div>
<p>Life expectancy appears to decrease with infant mortality, while decreasing only slightly with population size (<a href="#fig-reg-inf-mort-2000">Figure&nbsp;7</a>, <a href="#fig-reg-pop-2000">Figure&nbsp;8</a>). Using a definition of <span class="math inline">\(pvalue &lt; 0.05\)</span> as significance, it is evident that population size is a poor predictor of life expectancy (<span class="math inline">\(p = 0.6 &gt; 0.05\)</span>). However, infant mortality is in fact a better, significant predictor of life expectancy (<span class="math inline">\(p = 2 \times 10^{-8}\)</span>) (<a href="#tbl-lm_life_exp_inf_mort-2000">Table&nbsp;1</a>, <a href="#tbl-lm_life_exp_pop-2000">Table&nbsp;2</a>). Thus, we fail to reject the null hypothesis that life expectancy is not correlated with population size, but do reject the null hypothesis that life expectancy is not correlated with infant mortality rates.</p>
<section id="this-section-is-contributed-by-taylor-glass." class="level3">
<h3 class="anchored" data-anchor-id="this-section-is-contributed-by-taylor-glass.">This section is contributed by Taylor Glass.</h3>
</section>
</section>
</section>
<section id="exploring-the-dataset" class="level1">
<h1>Exploring the dataset</h1>
<p>I chose to explore the ‘movie’ dataset in the dslabs package. I used the help() function to find the description of the dataset and an explanation of the 7 variables it includes. I used the str() function to determine there are 100,004 observations of 7 variables. There are 4 integer variables, 1 character variable, 1 numeric variable and one factor variable with 901 levels. I used the summary() function to examine the range of each numerical variable. The year the movie was released ranges from 1902 to 2016. There are 6 distinct genres along with an ‘other’ option. The mean rating for all 100,004 movies included in the dataset is 3.544.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(<span class="st">"movielens"</span>) <span class="do">##learn about the dataset</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(movielens) <span class="do">##determine dimensions of dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100004 obs. of  7 variables:
 $ movieId  : int  31 1029 1061 1129 1172 1263 1287 1293 1339 1343 ...
 $ title    : chr  "Dangerous Minds" "Dumbo" "Sleepers" "Escape from New York" ...
 $ year     : int  1995 1941 1996 1981 1989 1978 1959 1982 1992 1991 ...
 $ genres   : Factor w/ 901 levels "(no genres listed)",..: 762 510 899 120 762 836 81 762 844 899 ...
 $ userId   : int  1 1 1 1 1 1 1 1 1 1 ...
 $ rating   : num  2.5 3 3 2 4 2 2 2 3.5 2 ...
 $ timestamp: int  1260759144 1260759179 1260759182 1260759185 1260759205 1260759151 1260759187 1260759148 1260759125 1260759131 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(movielens) <span class="do">##explore ranges for numerical variables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    movieId          title                year     
 Min.   :     1   Length:100004      Min.   :1902  
 1st Qu.:  1028   Class :character   1st Qu.:1987  
 Median :  2406   Mode  :character   Median :1995  
 Mean   : 12549                      Mean   :1992  
 3rd Qu.:  5418                      3rd Qu.:2001  
 Max.   :163949                      Max.   :2016  
                                     NA's   :7     
                  genres          userId        rating        timestamp        
 Drama               : 7757   Min.   :  1   Min.   :0.500   Min.   :7.897e+08  
 Comedy              : 6748   1st Qu.:182   1st Qu.:3.000   1st Qu.:9.658e+08  
 Comedy|Romance      : 3973   Median :367   Median :4.000   Median :1.110e+09  
 Drama|Romance       : 3462   Mean   :347   Mean   :3.544   Mean   :1.130e+09  
 Comedy|Drama        : 3272   3rd Qu.:520   3rd Qu.:4.000   3rd Qu.:1.296e+09  
 Comedy|Drama|Romance: 3204   Max.   :671   Max.   :5.000   Max.   :1.477e+09  
 (Other)             :71588                                                    </code></pre>
</div>
</div>
</section>
<section id="processingcleaning-data" class="level1">
<h1>Processing/cleaning data</h1>
<p>I decided to create a subset of this data with movie ratings from just the year that I was born, 2001. I used the filter function to create a new object called ‘mymovies’ with 3442 observations of 7 variables. I decided to explore the ratings among different genres of movies during 2001. I created a boxplot using genres as the categorical variable, which was very messy and not helpful. I decided to filter the datset further by only including movies in the drama and comedy genres, which limited the dataset to 319 observations of 7 variables. I selected the title, genres, and rating columns because they are the only variables useful for this analysis. When I created the second boxplot with the final dataset called ‘mymovies3’, it became easy to view the spread in ratings for drama and comedy movies released in 2001. The average rating for comedy movies is a 3, while the average rating for drama movies is a 4.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>mymovies <span class="ot">&lt;-</span> movielens <span class="sc">%&gt;%</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2001</span>) <span class="do">##limit dataset to movies released in 2001</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mymovies)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   3442 obs. of  7 variables:
 $ movieId  : int  4306 4308 4447 4718 4963 4995 4641 4975 4448 4886 ...
 $ title    : chr  "Shrek" "Moulin Rouge" "Legally Blonde" "American Pie 2" ...
 $ year     : int  2001 2001 2001 2001 2001 2001 2001 2001 2001 2001 ...
 $ genres   : Factor w/ 901 levels "(no genres listed)",..: 332 808 687 596 747 820 624 883 246 329 ...
 $ userId   : int  5 5 5 5 5 5 6 6 8 8 ...
 $ rating   : num  3.5 3.5 4.5 3.5 3 4.5 1.5 1.5 2.5 3.5 ...
 $ timestamp: int  1163374103 1163374354 1163375033 1163375131 1163373548 1163373616 1109258217 1109258226 1154400334 1154464808 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>mymovies <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>genres,  <span class="at">y=</span>rating)) <span class="sc">+</span> <span class="do">##use genres as the categorical variable and rating as the numerical variable</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">geom_boxplot</span>()   <span class="do">##create exploratory boxplot </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="coding-exercise_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>mymovies2 <span class="ot">&lt;-</span> mymovies <span class="sc">%&gt;%</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2001</span> <span class="sc">&amp;</span> genres <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Drama"</span>, <span class="st">"Comedy"</span>)) <span class="do">##further filter dataset to include 2 genres</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mymovies2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   319 obs. of  7 variables:
 $ movieId  : int  4718 4718 4225 4381 4388 4718 4723 4728 4816 4888 ...
 $ title    : chr  "American Pie 2" "American Pie 2" "Dish, The" "Closet, The (Placard, Le)" ...
 $ year     : int  2001 2001 2001 2001 2001 2001 2001 2001 2001 2001 ...
 $ genres   : Factor w/ 901 levels "(no genres listed)",..: 596 596 596 596 596 596 762 596 596 762 ...
 $ userId   : int  5 13 15 15 15 15 15 15 15 15 ...
 $ rating   : num  3.5 3.5 1 2 3 4 3.5 4 3 3 ...
 $ timestamp: int  1163375131 1331379530 997937762 997937346 1416119736 1044348492 1054449465 1044348492 1166586875 1054449355 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>mymovies3 <span class="ot">&lt;-</span> mymovies2 <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">select</span>(<span class="st">"title"</span>, <span class="st">"genres"</span>, <span class="st">"rating"</span>) <span class="do">##select 3 columns of useful information </span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mymovies3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   319 obs. of  3 variables:
 $ title : chr  "American Pie 2" "American Pie 2" "Dish, The" "Closet, The (Placard, Le)" ...
 $ genres: Factor w/ 901 levels "(no genres listed)",..: 596 596 596 596 596 596 762 596 596 762 ...
 $ rating: num  3.5 3.5 1 2 3 4 3.5 4 3 3 ...</code></pre>
</div>
</div>
</section>
<section id="create-a-few-exploratory-figures" class="level1">
<h1>Create a few exploratory figures</h1>
<p>I created the second boxplot with the final dataset called ‘mymovies3’, and it became easy to view the spread in ratings for drama and comedy movies released in 2001. I added a title for the boxplot and centered it to make it easier to read. The average rating for comedy movies is a 3, while the average rating for drama movies is a 4. I practiced saving this image to the folder previously created by Cora using the here() and ggsave() functions. To create another visualization of this data, I used the mean ratings from each category in a bar graph. The means of the ratings for each genre are displayed with better precision in this visualization. The mean rating for comedy movies is a little less than 3 at about 2.9 while the average rating for drama movies seems lower at about 3.5. This discrepancy could be explained by the 2 outliers shown in the drama category on the boxplot because these observations are skewing the mean. I saved this graph to the same folder with the boxplot using the here() and ggsave() functions. I also created a table of my final dataset to include the movie titles of both genres with each of their ratings from reviewers. It is a little busy since there are multiple reviews for the some of the same movies, so I organized it by title to allow for quick review of all the ratings provided for each movie. The first table has been commented out, so it will not print on this rendered website. It is included to show the process of creating the better table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>boxplot <span class="ot">&lt;-</span> mymovies3 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>genres,  <span class="at">y=</span>rating)) <span class="sc">+</span>   <span class="do">##visualize the ratings for each genre of movie </span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">geom_boxplot</span>() <span class="sc">+</span>    <span class="do">##create clean boxplot to compare ratings across genres in 2001</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>                <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratings for Drama and Comedy Movies in 2001 "</span>) <span class="sc">+</span>  <span class="do">##add a title to the graph</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="do">##center the title </span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>figure_file <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>, <span class="st">"results"</span>, <span class="st">"figures"</span>, <span class="st">"movies_boxplot.png"</span>) <span class="do">##inform R on where to save the image</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file, <span class="at">plot =</span> boxplot) <span class="do">##save the image in the predefined location </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ensure the figure renders on the website</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-inf-mort-all.  ##create a label for the final figure</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "life expectancy by infant mortality, Africa, 1960-2016."  ##create a label for the final figure</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: FALSE  ##ensure these lines are not reproduced in the rendered version</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>,<span class="st">"figures"</span>,<span class="st">"movies_boxplot.png"</span>)) <span class="do">##tag the saved location</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="results/figures/movies_boxplot.png" class="img-fluid" width="1050"></p>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>bargraph <span class="ot">&lt;-</span> mymovies3 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>genres, <span class="at">y=</span>rating)) <span class="sc">+</span> <span class="do">##visualize the ratings for each genre of movie</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>) <span class="sc">+</span>  <span class="do">##use the mean of each rating for the bars</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>                <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ratings for Drama and Comedy Movies in 2001"</span>) <span class="sc">+</span> <span class="do">##create a title for the graph</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="do">##center the title</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>figure_file2 <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"coding-exercise"</span>, <span class="st">"results"</span>, <span class="st">"figures"</span>, <span class="st">"movies_bargraph.png"</span>) <span class="do">##inform R on where to save the image</span></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> figure_file2, <span class="at">plot =</span> bargraph) <span class="do">##save the image in the predefined location</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ensure the figure renders on the website</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-inf-mort-all  ##create a label for the final figure</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "life expectancy by infant mortality, Africa, 1960-2016."  ##create a label for the final figure</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: FALSE  ##ensure these lines are not reproduced in the rendered version</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">"coding-exercise"</span>,<span class="st">"results"</span>,<span class="st">"figures"</span>,<span class="st">"movies_bargraph.png"</span>)) <span class="do">##tag the saved location</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="results/figures/movies_bargraph.png" class="img-fluid" width="1050"></p>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="do">## knitr::kable(mymovies3) ##create a table to display movie titles with their ratings</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="do">## comment out the first table so it will not show on the rendered website</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>better_table <span class="ot">&lt;-</span> <span class="fu">arrange</span>(mymovies3, title) <span class="do">##organize the table by title </span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(better_table) <span class="do">##view new table with all ratings for each movie grouped together by title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 84%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">title</th>
<th style="text-align: left;">genres</th>
<th style="text-align: right;">rating</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">61*</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">61*</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ali</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ali</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ali</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ali</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ali</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ali</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">All Over the Guy</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">All Over the Guy</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">All Over the Guy</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Pie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Rhapsody, An</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Rhapsody, An</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Animal, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Animal, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Animal, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Animal, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Animal, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Animal, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Animal, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Animal, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anniversary Party, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anniversary Party, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anniversary Party, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anniversary Party, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anniversary Party, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anniversary Party, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bad Guy (Nabbeun namja)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Believer, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Believer, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Believer, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Believer, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Blow Dry (a.k.a. Never Better)</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bubble Boy</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bubble Boy</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bubble Boy</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chelsea Walls</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chelsea Walls</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Closet, The (Placard, Le)</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Closet, The (Placard, Le)</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Curse of the Jade Scorpion, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Curse of the Jade Scorpion, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deep End, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deep End, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deep End, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deep End, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deep End, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diamond Men</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dish, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dr.&nbsp;Dolittle 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dr.&nbsp;Dolittle 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dr.&nbsp;Dolittle 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dr.&nbsp;Dolittle 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Emperor’s New Clothes, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Freddy Got Fingered</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Freddy Got Fingered</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Freddy Got Fingered</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Freddy Got Fingered</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Freddy Got Fingered</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Freddy Got Fingered</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Freddy Got Fingered</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Friends and Family</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grey Zone, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grey Zone, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hardball</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hearts in Atlantis</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts in Atlantis</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">How High</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">How High</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">How I Killed My Father (a.k.a. My Father and I) (Comment j’ai tué mon Père)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hush!</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">I Am Sam</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">In the Bedroom</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Invincible</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Iris</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Iris</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Josie and the Pussycats</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Josie and the Pussycats</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kandahar (Safar e Ghandehar)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kandahar (Safar e Ghandehar)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kandahar (Safar e Ghandehar)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">L.I.E.</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">L.I.E.</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">L.I.E.</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">L.I.E.</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lammbock</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Life as a House</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Life as a House</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Life as a House</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Life as a House</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Life as a House</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Life as a House</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Life as a House</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Life as a House</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lost and Delirious</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lost and Delirious</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Made</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Made</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Made</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Made</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Made</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manic</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not Another Teen Movie</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nowhere in Africa (Nirgendwo in Afrika)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nowhere in Africa (Nirgendwo in Afrika)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nowhere in Africa (Nirgendwo in Afrika)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nowhere in Africa (Nirgendwo in Afrika)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nowhere in Africa (Nirgendwo in Afrika)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">On the Edge</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">One Night at McCool’s</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">One Night at McCool’s</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">One Night at McCool’s</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Piano Teacher, The (La pianiste)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Piano Teacher, The (La pianiste)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Piano Teacher, The (La pianiste)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Piano Teacher, The (La pianiste)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Piano Teacher, The (La pianiste)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Piano Teacher, The (La pianiste)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Piano Teacher, The (La pianiste)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Piñero</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Piñero</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rat Race</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rat Race</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rat Race</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rat Race</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rat Race</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rat Race</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rat Race</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rat Race</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scary Movie 2</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">See Spot Run</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shipping News, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shipping News, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shipping News, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shipping News, The</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Son’s Room, The (Stanza del figlio, La)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Son’s Room, The (Stanza del figlio, La)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sugar &amp; Spice</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sugar &amp; Spice</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taking Sides</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tape</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tape</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tape</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tape</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The Last Brickmaker in America</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Things Behind the Sun</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Thirteen Conversations About One Thing (a.k.a. 13 Conversations)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thirteen Conversations About One Thing (a.k.a. 13 Conversations)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Thirteen Conversations About One Thing (a.k.a. 13 Conversations)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thirteen Conversations About One Thing (a.k.a. 13 Conversations)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Thirteen Conversations About One Thing (a.k.a. 13 Conversations)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thirteen Conversations About One Thing (a.k.a. 13 Conversations)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">To the Left of the Father (Lavoura Arcaica)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tomcats</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Town &amp; Country</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wash, The</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Waterboys</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wet Hot American Summer</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wet Hot American Summer</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wet Hot American Summer</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wet Hot American Summer</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wet Hot American Summer</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wet Hot American Summer</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">What Time Is It There? (Ni neibian jidian)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">What Time Is It There? (Ni neibian jidian)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">White Sound, The (Das weiße Rauschen)</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wit</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wit</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wit</td>
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zoolander</td>
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">4.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="simple-statistical-model" class="level1">
<h1>Simple statistical model</h1>
<p>I decided to conduct a simple t test to determine if the mean ratings among movies in each genre are statistically different from one another. I created an object called ‘drama’ to pull the ratings for movies in the drama genre from the dataframe. I did the same thing for movies in the comedy genre and saved that object as ‘comedy’. I used the base R t.test() function to compare the average ratings between the two groups and printed the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>drama <span class="ot">&lt;-</span> mymovies3<span class="sc">$</span>rating[mymovies3<span class="sc">$</span>genres <span class="sc">==</span> <span class="st">"Drama"</span>] <span class="do">##create an object with ratings only for movies in drama genre</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>comedy <span class="ot">&lt;-</span> mymovies3<span class="sc">$</span>rating[mymovies3<span class="sc">$</span>genres <span class="sc">==</span> <span class="st">"Comedy"</span>] <span class="do">##create an object with ratings only for movies in comedy genre</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>t.test1 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(drama, comedy) <span class="do">##run a two-sample t-test between the two numeric vectors</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t.test1) <span class="do">##show the results of the t-test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  drama and comedy
t = 4.6912, df = 279.12, p-value = 4.257e-06
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 0.3433740 0.8398837
sample estimates:
mean of x mean of y 
 3.504000  2.912371 </code></pre>
</div>
</div>
</section>
<section id="results-of-simple-statistical-model" class="level1">
<h1>Results of simple statistical model</h1>
<p>After running the two-sample t-test, I get a test statistic of 4.6912 with a tiny p-value of 4.257e-06. Since the p-value is much less than 0.05, we can reject the null hypothesis to conclude that there is a statistically significant difference between the mean ratings of drama and comedy movies in 2001. It is clear that movies in the drama genre received higher ratings from viewers compared to movies in the comedy genre in 2001.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>